gef.py
Some certain terminal may not display gray color well without this '1;'. (At least under my Konsole/zsh and i3's terminal)
=> Fixed problems when displaying text in gray.

gef.py
Use RL_PROMPT_START_IGNORE and RL_PROMPT_END_IGNORE sequences.
=> Instruct readline to ignore length of color control characters.

docs/features.md, gef.py
This adds a new option to `edit-flags` so you can toggle instead of just set or unset.
This is handy, for example, if you want to alternate which branch you take every time you hit it
```bash
b <x>
commands 1
edit-flags ~ZERO
end
```
=> edit-flags: Add toggle feature

gef.py
This should fix the issue according to https://github.com/sploitfun/lsploits/blob/master/glibc/malloc/malloc.c#L4537.
Let me know if you want me to run any sort of extra-testing or whatnot :-).
Cheers
=> #58: computing the heap chunk usable size according to musable in glibc-malloc

docs/features.md, gef.py
Hi, I've added a new option to gef-remote so you can tell the gdbserver which executable you want to run. Additionally this patch allows you to restart processes and specify arguments (when you are connected in extended-remote mode).
Example (server started with `gdbserver --multi 0.0.0.0:1337`):
```
gef➤  gef-remote -f /bin/ls 10.0.0.83:1337
[+] Connected to '10.0.0.83:1337'
Reading /bin/ls from remote target...
warning: File transfers from remote targets can be slow. Use "set sysroot" to access files locally instead.
Reading /bin/ls from remote target...
[+] Target is not running, waiting for start
gef➤  run "/proc"
`target:/bin/ls' has disappeared; keeping its symbols.
Starting program: target:/bin/ls "/proc"
Reading /lib/ld-linux.so.2 from remote target...
Reading /lib/ld-linux.so.2 …
```
=> added support for remotely specifiying debugee and re-running targets

gef.py
The `_type` conversion was not saved, making setting non-string,
non-bool settings not work as expected.
=> Fix setting non-string config

gef.py
Floor division was used in two different ways. This lets you not worry about it.
=> Use future (python3 style) division

docs/index.md
Updated Keystone installation instructions from git please see:
https://github.com/keystone-engine/keystone/blob/master/docs/COMPILE-NIX.md
The previous instructions will give import errors and a broken keystone installation.
Currently installation of keystone with pip is not working as well but the git installation works fine.
Hope it helps.
--lillypad
=> Updated Keystone Installation

gef.py
I think you made a mistake in this format string. `.format` seems to count the "0x" in padding while ` % (fmt)` does not, so I had to increate the padding to account for it. You also switched it from zero padded to left aligned, which I don't think you want incase a dump goes over a nybble border.
```python
>>> x = 0x500
>>> "%#-.*X" % (16, x) # Original
'0X0000000000000500'
>>> "{:<#16x}".format(x) # Yours
'0x500           '
>>> "{addr:#0{aw}x}".format(addr=x, aw=16) # Mine with 16
'0x00000000000500'
>>> "{addr:#0{aw}x}".format(addr=x, aw=18) # Mine with 18
'0x0000000000000500'
```
=> Fix padding in one format string plus trim a few lines

docs/commands.md
Fixed the broken table in `commands.md` caused by having line breaks on some rows. Unfortunately this lead to some pretty long lines in places which makes the Markdown fairly ugly but I couldn't find a workaround for this. At least the table is readable now :)
Relates to: https://github.com/hugsy/gef/issues/86
=> Fix table formatting in commands.md

docs/index.md, gef.py
* Fixes a bug on python3 gdb when printing heap arenas.
* Fixes other format strings that were converting a string to an int only to convert it to a string again.
* Fixes a few typos.
* Improves (imo) some wording in the comments, prints, and README.
* Should have some speed improvements (untested).
https://github.com/hugsy/gef/issues/97
=> Fix bad format string in heap dump 

gef.py
Fixes indentation error at line 4946 which prevents gdb from loading the .gdbinit-gef.py script.
Love the project I use this all the time, I'll buy you beer if we meet up someday.
Cheers!
##IndentationError: expected an indented block Fix ##
Fixes indentation error at line 4946 which prevents gdb from loading the .gdbinit-gef.py script.
https://github.com/hugsy/gef/issues/XX
Fixes indentation error currently script does not launch with gdb 7.x
GDB will be able to launch the .gdbinit-gef.py making life hella awesome duh.
Has this patch been tested on:
Linux d3d53c 4.4.39-gentoo #1 SMP Mon Jan 16 17:26:37 AST 2017 x86_64 Intel(R) Core(TM) i7-6560U CPU @ 2.20GHz GenuineIntel GNU/Linux …
=> IndentationError: expected an indented block Fix

gef.py
Instead of only looking in the current block for symbols, work up to the static block. This way, you can dump more information.
```bash
─────────────────────────────────[ source:array.c+11 ]────
7            memset(ar, '\x00', 20);
8            memset(ar, '\x00', 20);
9
10            for (int i = 0; i < 20; i++)
// i=0x0, ar=0x00007fffffffe490  →  0x00
11                    printf("%02x ", ar[i]);                   ←  $pc
12            printf("\n");
13     }
```
without:
```bash
────────────────────────────────[ source:array.c+11 ]────
7            memset(ar, '\x00', 20);
8            memset(ar, '\x00', 20);
9
10            for (int i = 0; i < 20; i++)
11                    printf("%02x ", ar[i]);                   ←  $pc        ; i=0x0
12            printf("\n");
13     }
```
=> context_code: Work up the hierarchy when dumping symbols

gef.py
Add `printchar` or `pchar` command.
Quick and dirty replacement for `p/c` which is broken.
=> Add pchar command to replace p/c

docs/commands/context.md, gef.py
* is_hex: EAFP style check
* Minor cleanups
* Context: Add 'peek call' option
```
0x8048d16    push 0x8049df0
→ 0x8048d1b    call 0x8049ed0
↳  0x8049ed0    push ebp
0x8049ed1    mov eax, 0x0
```
* Registers: Highlight changed regs
* Cast registers to unsigned in get_register
GDB types registers, meaning $esp and $eax, for example, can have the
same value, but evaluate to different values (eax being negative, esp
always unsigned). This casts the value to an unsigned.
This fixes DereferenceCommand not showing when other registers point to
an address.
```
─────────────────────────────────────[ stack ]────
0xffffd600│+0x00: 0x08049df0  →  0x8049df0    lea ecx, [esp+0x4]         ← $esp
0xffffd604│+0x04: 0x01   ← $eax  // Before this would never show
```
* context_source: Put pc arrow on left
* …
=> Change context_code and context_source arrows to left side + peek code

gef.py
modified:   gef.py
Just some minor changes to heap command when no symbols found.
the get_main_arena function wants to handle a gdb.error when no symbols(especially malloc_state_t) found, but the GlibcArena class just gives back a None which will cause further calling on None object used as malloc_state_t and caues unwanted exception.
And also did some changes to the error messages since when that happens, it may also be no symbols found instead of incorrect glibc arenas only.
=> fix wrong error handling when no main_arena found

docs/commands.md, docs/commands/memory.md, gef.py
`memory watch ADDRESS [SIZE] [GROUPING]`
`memory unwatch ADDRESS`
`memory list`
`memory clear`
Can be added to your context layout.
```
──────────────────────────────────────────────────────────────────────────────[ stack ]────
0x00007fffffffe560│+0x38: 0x00007fffffffe7a9  →  "USER=vagrant"
────────────────────────────────────────────────────────────────────[ memory:0x620000 ]────
0x0000000000620000     00 00 00 00 00 00 00 00 01 10 02 00 00 00 00 00     ................
0x0000000000620010     0c 24 ad fb 00 00 00 00 00 00 00 00 00 00 00 00     .$..............
0x0000000000620020     00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................
0x0000000000620030     00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00     ................ …
```
=> Add rudimentary memory context view and mem watch command

gef.py
1. Allow hexdump to group by variable amounts (e.g. word, dword, qword)
2. Remove the special handling in the hexdump _command_ for non-byte sizes
3. Evaluate simple expressions in memory command.
4. Don't require L in front of size arg of hexdump
5. Allow size to be specified in hex in size arg of hexdump
6. Fix usage cases in xor-memory command.
Still needs to be tested on python2! specifically: `hexdump qword`
=> Improve hexdump function and commands that use it

gef.py
The get_filepath() method used to work on the assumption that the inferior in gdb would always have a name which can be false. In that case a NoneType was returned and later dereferenced resulting in an error.
The patch fixes this by checking in the else branch if filename is None and if yes, uses 'info proc' to retrieve the cmdline
None
Resolves execution error in case of inferior not having a name
This patch was only tested on a x86_64 machine specifically on a 64bits process (firefox) as I ran into the situation inadvertently.
| x86-32       | No       |          |
| x86-64       | Yes |                        |
| ARM          | No      | …
=> Fix get_filepath when inferior has no name

gef.py
modified:   gef.py
A very simple patch so that we can specify "S" argument when using hexdump command to get symbols displayed.
None
When we use gdb's "x" command to read memory, we can get symbols there when possible. But we can't get those symbols when using hexdump command. Sometimes we do need those symbols, and we have to use an extra "x" command of gdb to get those. We don't really need that.
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] My code follows the code style of this project.
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ x ] I have read and agree to the **CONTRIBUTING** document.
=> Add display symbols option of hexdump command

gef.py
This patch fix problem with `context` command if `memory watch` is enabled for some address (see screenshots). This problem appeared after commit https://github.com/hugsy/gef/commit/f3cfded314e5a28661c7ec749747e1d45d09d94e, in which there is a call of `hexdump` function with keyarg `fmt` in method `ContextCommand.context_memory`.
This patch fix bug in `context` command.
| x86-32       | :heavy_check_mark:       |            |
| x86-64       |:heavy_check_mark: |                        |
| ARM          |  :heavy_multiplication_x:      |                        | …
=> Fix watch memory

gef.py
After `ropper` call, autocomplete function stops working correctly. Instead of gef/gdb command it autocomplete python environment entitiy. This happens because `ropper` imports `rlcompleter` module, which set up own completer function in `readline` module. In my patch completer function (and completer delims) is backed up before `ropper` call and restored after it.
| x86-32       | :heavy_check_mark:       |           |
| ARM          | :heavy_multiplication_x:        |                        | …
=> Fix autocompleter problem

docs/commands.md, docs/commands/pie.md, gef.py
This is what I've done to support PIE, this is actually pretty naive implementation.
Since PIE base address is known only when we start a program, then I implemented `pie run`, `pie attach`, `pie remote` to substitute original `run`, `attach` and `remote` commands. Then I can start a program and then decide its base address to set my real breakpoints. This is done by commands `pie breakpoint`.
I call those "virtual" breakpoint "PIE breakpoint". I have searched for some time but have no clue about how to do pre hook to something like starting a program. That is why I used such a method. 
https://github.com/hugsy/gef/issues/183
Currently gef has no complete PIE support, and every time I want a breakpoint of a PIE program I have to do `entry-break` and then find out base address to calculate …
=> [RFC]pie breakpoint support

gef.py
This prints a nice error message if -a or -m is missing when running the `assemble` command
#185 
This is way better than showing an ugly python exception.
Yes, works on my laptop. Anyway, it's 4 lines of python.
=> Issue #185: Improve error message if -a or -m is missing

gef.py
`gef_get_auxiliary_values()` parses the values returned by "info auxv"
as hexadecimal, which is wrong. This patch uses `base=0` to infer the
correct base depending on the prefix ("0x" for hex, otherwise decimal)
#186 
Tested on my laptop, with gdb 8.0.1 and python 3.6.
`base=0` also works on python 2.7
=> Issue #186: gef_get_auxiliary_values() assumes values are in hexadecimal

gef.py
Change `instruction_length` of ARM:thumb to `None` from 2, Thumb has no fixed size instructions.
This fixes some problems with the context code for ARM thumb.
ARM
=> ARM thumb has variable instruction sizes

gef.py
Fixes a bug where 1 byte wide instructions are not shown in the code context when `context.nb_lines_code == 1`:
note the missing line with `clc` before the current instruction (this is after a `stepi`)
The range of addresses used as start point for instruction disassembly in `gdb_get_nth_previous_instruction_address` had a lower limit of 2 because the second argument to `range` is exclusive.
x86-64
=> also look for 1 byte wide instructions in gdb_get_nth_previous_instruction_address

gef.py
Small fix in the way gef parses second argument 
https://github.com/hugsy/gef/issues/211
Fixes the bug
| x86-32        | :heavy_multiplication_x: | does not apply |
| x86-64        | :heavy_multiplication_x: | does not apply |
| ARM           | :heavy_multiplication_x: | does not apply |
| AARCH64   | :heavy_check_mark:        | Fix in AARCH64.is_branch_taken |
| MIPS          | :heavy_multiplication_x:  | does not apply |
| POWERPC  | :heavy_multiplication_x: | does not apply |
| SPARC        | :heavy_multiplication_x: | does not apply |
=> Fix failure to parse operand1 as int for TNBZ/TBZ aarch64 instruction

gef.py
Bugfix: The wrong argument is checked if it is a digit if a size is provided with the pattern offset command
Bugfix
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the code style of this project.
- [x ] I have read and agree to the **CONTRIBUTING** document.
=> Bugfix: Invalid size printed because of checking wrong argument

gef.py
The way that command-specific settings were read was very slow. Every
setting read would have to filter through all settings twice.
This change avoids building the filter when possible.
Also, since it was only ever used for the name of the settings, return a
list of names instead of a dict of name:value.
This can speed up the context command by as much as 25%
Before:
1       0.001   0.001   2.423   2.423   profile:0(ctx.do_invoke(""))
After:
1       0.001   0.001   3.311   3.311   profile:0(ctx.do_invoke(""))
=> Fix slow settings retrieval

gef.py
The context command calls `get_info_files` 50+ times (Unless you're
showing regs raw, and who wants that?).
This appears to speed up the context command for me 25% on my linux
(x86_64) machine and 40% on my raspberry pi!
=> Cache get_info_files for big speedup!

gef.py
Fix `pie breakpoint` bug when using on running process. Currently when using `pie breakpoint` on running process, no real breakpoint will be set until next `pie run` or `pie attach`.
Fix `pie breakpoint` bug when using on running process
Fix the bug by adding breakpoint set code when alive process is detected when using `pie breakpoing`
Nope.
Bug repair
| x86-32       | :heavy_multiplication_x:       |             |
| x86-64       | :heavy_check_mark: | rock'n roll                       |
| ARM          | :heavy_multiplication_x:       |                        | …
=> Fix `pie breakpoint` bug when using on running process

gef.py
Fixes #245
Headless servers have zero width screens. This was making the width calculation negative, which generated a illegal format string.
=> Use max() to avoid zero or negative numbers

scripts/ida_gef.py
__long__ was removed in Python 3 in favor of __int__.
=> ida_gef.py: Define long() in Python 3

docs/index.md, scripts/gef-extras.sh
Add an install script for gef-extras, nothing special, just automating the more than 1 instructions needed if anyone wants to do it easily.
It clones the `gef-extras` repo to `$HOME`, then setting `gef.extra_plugins_dir` and `pcustom.struct_path`.
https://github.com/hugsy/gef/issues/252
One line installation for gef-extras just like gef itself!
No testing required.
=> scripts: Add install script for gef-extras

gef.py
Just replaces '-' by '.' in the version number to make it to integers again. This is sufficient as only major and minor version numbers are used. 
It makes gef installable if gdb version contains a '-', which was the case after I upgraded to Fedora 28. …
=> Fix version handling to work with '-' in version number

docs/commands/unicorn-emulate.md
`-e` doesn't exist, `-o` does and what `-e` claims to.
docs are old. this makes them new. new is better than old
- [x ] My code follows the code style of this …
=> unicorn docs referenced outdated option

gef.py
=> Fixed heap help message typo

docs/commands/pcustom.md, gef.py
Currently the user can specify how to substitute values in a struct using `_values_` in the pcustom struct file.
In addition to the current ability to substitute values using a list of tuples, after this patch the user can also specify a function to do the substitution,  giving more flexibility.
An example of this being used is in the [socketaddr_in](https://github.com/hugsy/gef-extras/pull/8/files#diff-949c9b64b64de1131b192b7bd065b4ae) struct.
https://asciinema.org/a/0iygyS51V8j6dLmft243wABGq
Tested using the [socketaddr_in](https://github.com/hugsy/gef-extras/pull/8/files#diff-949c9b64b64de1131b192b7bd065b4ae) struct.
| x86-32       | …
=> Allow user to specify substitution function in pcustom struct

gef.py
As mentioned in #285, descriptions for a command is not shown when doing `gef` if there is a newline at the start of the doc string.
Added a newline to doc string of `is-syscall` to show that it works. …
=> Fix multiline doc string not showing description

gef.py
Occasionall would get the following:
`[!] Command 'dereference' failed to execute properly, reason: 'NoneType' object has no attribute 'path'`
Was broken in https://github.com/hugsy/gef/commit/edbadbef7813fb96827572fcac3db35c9550beaa
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hugsy/gef/287)
=> ensure that section has a path attribute

docs/commands/hijack-fd.md, gef.py
Like what is mentioned in #139, in addition to be able to open a file, if it detects `:` in the second
arg, it will make a `connect` call to the given address and port.
The user could spoof a web server that an application under testing is connecting to. Or, just open another terminal to provide input/receive output more cleanly.
https://asciinema.org/a/0dizAXevliwGYboibPUJmJntO …
=> hijack-fd: Support connecting to ip:port

gef.py
1.
The old implementation of `to_unsigned_long` was wrong, you can test it by passing something like 0xffffffffffffffff, and it will return -1. 
And I did not find an elegant way to resolve this problem. So I cast `gdb.Value` to `str` and then cast back to `long`.
2.
Catch annoying error message when key error occurred during running `syscall-args`
3.
There was a display bug when running `registers` command on 64bit machines because of wrong masking.
4.
There should be a warning message to remind user where to download syscall table(gef-extra). But I'm not sure whether it is a better idea to include it in gef since `syscall-args` has been integrated into gef.
=> Fix unsigned long cast problem and fix some problems in `syscall-args` command

docs/index.md, gef.py
ida-interact was throwing errors when the file contained a space because it was not properly matching with vmmap
line 4596 was throwing errors due to min being passed 0 args
yes
- [ x] My code follows the code style of this project.
- [ x] My change includes a change to the documentation, if required.
- [ x] I have read and agree to the **CONTRIBUTING** document.
=> fix bug where improper spaces where being stripped

gef.py
Before this, `pie breakpoint` is not fully working.
```
gef➤  pie breakpoint 0x8FD
[!] Function "0x8FD" not defined.
gef➤  info breakpoints
No breakpoints or watchpoints.
gef➤  pie breakpoint *0x8FD
[!] Function "0x8FD" not defined.
```
This PR is to fix those issue
| x86-32       | :heavy_check_mark: : | Replace with :heavy_check_mark: if tested | …
=> pie breakpoint parse address using gdb.parse_and_eval

gef.py
Fixes #312 
Basically on CI `python` was `python3`. This pointed out to us that the unicorn script we generate doesn't work correctly on python3. This change fixes the script, and also uses the same version of python running in gdb outside of gdb to execute the script.
=> emu: Use matching python version and use bytes in disasm

gef.py
Currently when running commands like `telescope` or `hexdump` and you press return a second time the same command is run again. This PR adds a boolean property called `repeat` to `GenericCommand` allowing commands handlers to know whether the user had repeated the command by just pressing return.
This allows for behaviour similar to gdbs `x` where you can keep scanning through memory by just pressing return.
Currently this PR used the new property in `DereferenceCommand` and `HexdumpCommand` to advance the start address on a repeat.
| x86-32       | :heavy_multiplication_x: |                         | …
=> Advance the address instead of repeating for memory commands

gef.py
I didn't like the way that hexdump showed offsets. I make it more obvious and colourful.
Old:
New:
=> Hex like deref

docs/commands.md, docs/commands/functions.md, gef.py, mkdocs.yml, tests/binaries/bss.c, tests/runtests.py
Quite often when debugging we need to print out the heap or an offset from the heap, and having to run `vmmap` to get the base address and copy/paste can be annoying. [GDB convenience functions](https://sourceware.org/gdb/onlinedocs/gdb/Functions-In-Python.html#Functions-In-Python) are just like convenience variables and can be used as arguments to other commands:
This PR adds functions for (offset is optional):
* `$_heap(offset)`
* `$_pie(offset)`
* `$_stack(offset)`
* `$_bss(offset)`
* `$_got(offset)`
Happy to change or discuss the naming convention for these, this is just how the gdb built-in functions are (eg `$_strlen(str)`)
There's no doco or tests yet, just wanted to get any initial feedback first and then I'll make any changes and add them.
| Architecture | Yes/No …
=> Add gdb convenience functions for working with heap and other randomised section addresses

gef.py, tests/runtests.py
Allow `hexdump q` instead of forcing `hexdump qword`, etc.
=> hexdump: Allow shorter form for size and direction

gef.py
Fixes https://github.com/hugsy/gef/issues/302 and https://github.com/hugsy/gef/issues/303
Tested using `./gdbserver-7.7.1-armel-eabi5-v1-sysv 0.0.0.0:12345 ./thumb_demo` in an arm_now `armv7-eabihf` machine.
cs in ARM mode:
cs in THUMB mode:
asm in ARM mode:
asm in THUMB mode:
emu in ARM mode:
emu in THUMB mode:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hugsy/gef/343)
=> set mode based on current thumb flag

docs/index.md, gef.py
In context_regs and 'registers' command, instead of colouring the value
of the register based on whether it changed since the last stop, colour
the name. This allows us to colour the value based on the section, as we
do with `deref`.
=> Show changed reg colour in name and section in value

gef.py
The ops for a `call` instruction may be something like the following.
```
call <func_name at filename.c:42>
```
The current regex will attempt to lookup the global symbol "func_name at
filename.c:42". Instead we should lookup just "func_name".
| AARCH64      | :heavy_check_mark: |                        | …
=> Update target function regex

gef.py
| AARCH64      | :heavy_check_mark: : |                        |
Example:
```
.section .text
.global main
main:
mov x1, #0x8
mov x0, x1, LSL #0x1c
cmp x0, #0
bhi correct
ret
correct:
cmp x0, #0
bls incorrect
mov x0, #0
incorrect:
ret
```
=> AAarch64: Add the `hi` and `ls` conditions to the conditional branch logic

gef.py
Found while testing https://github.com/hugsy/gef/pull/338 on python 2, all commands return the following:
```
------------------------------- Exception raised -------------------------------
AttributeError: 'NoneType' object has no attribute '__module__'
----------------------------- Detailed stacktrace ------------------------------
\-> File "/usr/lib/python2.7/functools.py", line 33, in update_wrapper()
->    setattr(wrapper, attr, getattr(wrapped, attr))
\-> File "/home/will/github/gef/gef.py", line 308, in bufferize()
->    @functools.wraps(f)
\-> File "/home/will/github/gef/gef.py", line 3611, in invoke()
->    bufferize(self.do_invoke(argv))
```
I'm not really sure what `bufferize` does but we are currently always passing it `None` instead of a function, as it's getting the return …
=> bufferize takes a function

gef.py
sometimes I can encounter this problem `Getting a string is unsupported in this language`.
And according #301 , it is because gdb cannot retrieve string in obj-c. So I add a fallback to this function so it can read string as expected.
And this patch resolves #301
| SPARC …
=> fallback to read memory when gdb api fails to retrieve a cstring

gef.py
@wbowling noticed that if you get a command to fail, all subsequent commands break.
This is because when the bufferize wrapper calls the function, if there's an unhandled exception, then it won't fix `sys.stdout`.
Simply moved the stdout repair into a finally block.
=> Fix bufferize

gef.py
Fixes #360 
On ARM, AARCH64, and x86 we were not correctly comparing if two flags
were equal: Because we were comparing the masked value instead of
whether the bit was set, these would NEVER be true.
For example for `ge` on x86, the branch is taken is SF==OF, but we were
comparing  flags&(1<<7) == flags&(1<<11). Even if both flags were set,
we'd be comparing 0b10000000 with 0b100000000000, which would never be
true.
This assumes that gdb prints conditionals in a certain way (e.g. `ble` not `bleq`). This needs to be tested.
=> Fix arm and x86 conditionals

gef.py
Add basic tcache support.
Super ugly for now.
`dereference_as_long` seems to be broken in my case: When I deference the start of the chain, I get the original address back. I have no idea how this function ever works. I use `read_memory` directly.
~This doesn't work with bufferize! We parse out the libc version, but if we are bufferizing, `gdb.execute("vmmap libc")` returns an empty string, so we can't get the version. See #362.~
^ We use `get_process_maps` to sidestep this issue.
- ~[ ] Merge after #364: This'll allow this to work without having to disable buffering.~
=> Add tcache support

gef.py
When stepping through a ROP chain if found that `gef_disassemble` calls `gdb_get_nth_previous_instruction_address` which could return `-1` causing the following:
I think `None` is more appropriate and `gef_disassemble` already checks for it fixing the issue:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hugsy/gef/370)
=> context_code unable to disassemble $PC

gef.py, tests/runtests.py
I fixed the hardcoding of malloc in the TraceMallocRetBreakPoint class to pull it's name from self.name in TraceMallocBreakpoint. I also updated the test cases to now look calloc(32). 
`__libc_malloc(16)=0x555555756010\n[+] Heap-Analysis - __libc_malloc(16)=0x555555756010\n[+] Heap-Analysis - __libc_calloc(32)=0x555555756030\n[+] Heap-Analysis -`
=> Issue #359 Fixed Heap Analysis Hard Coding Malloc In BreakPoint

.circleci/config.yml, docker/Dockerfile
#342 
I created a custom Docker container per the CircleCI docs on recommended caching method. Their internal caching system is a bit limited and they recommend just building an image.
With the custom container this brought the build down to 1:58. With the docker image itself cached it was brought down to 1:51
I also created a docker folder in the root of the project that contains the Dockerfile and docker-compose.yml that way if the image needs to be removed to a repo not controlled by me it won't be difficult to do.
=> Issue #342 Caching all project dependencies with custom docker container

gef.py
A lot of ctfs provided a libc to use, and currently gef requires debug symbols in order for the heap commands to work (it uses `struct malloc_state`)
The aim is to have the heap commands work without debug symbols, and even in a stripped binary with no `main_arena`
~Need to add 32bit, tests, and clean up `get_main_arena_address`~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hugsy/gef/373)
=> heap commands with no symbols

gef.py
To solve the register misaligned problem in show_registers_raw mode, I did the following modification:
- format the flag value with `format_address_spaces()`
- correct `l += current_arch.ptrsize` to `l += current_arch.ptrsize * 2`
=> Fix register misalignment in show_registers_raw mode

gef.py, tests/binaries/Makefile, tests/binaries/heap-non-main.c, tests/runtests.py
While doing a recent CTF I ran into a few issues when dealing a thread arena:
* NON_MAIN_ARENA wasn't cleared from the chunk size
* heap bin commands didn't work as `(int(arena)&~0xFFFF) == (bk&~0xFFFF)` was always true
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hugsy/gef/392)
=> Non main heap arena fixes

gef.py
We constant disable and reenable logging/redirection. Apparently we are
disabling it in the wrong order, which in GDB 8.1 causes issues.
=> Fix disable_redirect_output to fix #383

gef.py
The const `BIG_ENDIAN` in `class ELF` should be 2 instead of 0. According to `ELF_Format.pdf` (from Ref comment) `e_ident[EI_DATA]` is either 1 for LSB or 2 for MSB.
| MIPS         | :heavy_check_mark: | encountered this bug while trying to get unicorn-emulation working on ELF 32-bit MSB, MIPS executable                       |
| SPARC …
=> elf class bugfix

gef.py
On a system with **gdb 7.6** and python 2.7, I get this nice traceback trying to install Gef:
```
Traceback (most recent call last):
File "~/.gdbinit-gef.py", line 9473, in <module>
TypeError: sequence item 0: expected string, int found
```
Of course it's because `str.join('.', (7,7) )` doesn't work -- it needs the ints stringified. The fix is trivial, see diff.
In such a good project, having implemented the version check, you certainly don't want it to crash!
Manually, on Python 2.7.5 and Python 3.6.7.
=> Fix crash on Old GDB warning

docs/commands/context.md, gef.py
Quite often after doing a few derefs or anything at a breakpoint, you want to look at part of the context again. This allows you to specify a single or multiple sections to show:
```
gef➤  context -h
[!] Syntax
context [legend|regs|stack|code|args|memory|source|trace|threads|extra]
gef➤  context code
─────────────────────────────────────────────────────────────────────────────────────────── code:x86:64 ────
0x7ffff743dbef <poll+63>        mov    rdi, rbx
0x7ffff743dbf2 <poll+66>        mov    eax, 0x7
0x7ffff743dbf7 <poll+71>        syscall
→ 0x7ffff743dbf9 <poll+73>        cmp    rax, 0xfffffffffffff000
0x7ffff743dbff <poll+79>        ja     0x7ffff743dc32 <__GI___poll+130>
0x7ffff743dc01 <poll+81>        mov    edi, r8d
```
| Architecture | Yes/No                   | Comments …
=> Context sub commands

docs/commands/scan.md, gef.py
Currently there is no way to scan sections without a pathname, such as mmap anonymous mappings. This adds the ability to specify address ranges in the format `start-end` for the `scan` command.
| x86-32       | :heavy_multiplication_x: | :heavy_check_mark: |
| x86-64       | :heavy_multiplication_x: | :heavy_check_mark:  | …
=> Allow specify address range in `scan` command

docs/commands.md, docs/commands/highlight.md, docs/screenshots.md, gef.py, mkdocs.yml, tests/helpers.py, tests/runtests.py
This was created to identify memory addresses & strings while examining registers, hex dumps and heap layout.  Coloring the output seems to improve recognition speed during exploitation.
Further explanation may be found here - https://github.com/pwndbg/pwndbg/issues/366
A new command has been added called `highlight` and includes aliases `hh` & `hl`.
With this command you can add/remove/list matches associated with colors.
Example highlights using common identifiers (`41414141`, `42424242`, etc.):
| x86-32       | :heavy_check_mark: | |
| ARM          | :heavy_check_mark: | by  @hugsy …
=> add custom match highlighting

gef.py
Fix #430 
This is how checksec.sh does it. If `GNU_RELRO` is absent, then `Full RelRO` won't be set regardless of the presence of `BIND_NOW`.
https://github.com/slimm609/checksec.sh/blob/3eff9b7d4641a34d1eb5f6d9201899d6bca6c08e/checksec#L276-L285
In gef this was inaccurate because the presence of `BIND_NOW` was checked even when `GNU_RELRO` was absent.
Not sure whether this should target `master` since it is a bugfix. …
=> Fix checksec inaccuracy with RelRO

docs/commands/search-pattern.md, gef.py
This adds an argument for the command `search-pattern` (`grep`, `xref`) for the user to choose an address range or section to search from.
This is because sometimes one may need to search for a very common pattern, and having the terminal flooded with output is troublesome.
This argument comes before the one for endianness. To set endianness without limiting the search space, `grep 0x400123 memory big`.
| x86-32       | :heavy_multiplication_x: | :heavy_check_mark: |
| x86-64       | :heavy_multiplication_x: | :heavy_check_mark: | …
=> Add search range for `search-pattern`

gef.py
Currently, the return value of `connect()` or `open()` is unsigned. To determine whether there was an error, the returned `fd` will be compared with -1. However since `fd` is unsigned, the error will never be detected.
To fix this, `fd` is converted to signed before performing the check.
| x86-64       | :heavy_multiplication_x: | :heavy_check_mark:| …
=> hijack-fd: Convert fd to signed integer

gef.py
@wbowling noticed that if a register points to a block of memory without nullbytes, when registers are not shown raw, the deref takes long. It's because `read_cstring_from_memory` keeps reading until it finds a null byte.
This change caps how far ahead it'll read, which should speed things up a lot in those cases.
=> read_cstring: Cap length of string cast

docs/commands/dereference.md, docs/commands/hexdump.md, gef.py, tests/runtests.py
This sets the address stored in stack register as default argument for dereference and hexdump commands, and makes the arguments position-independent. In addition, it sets the byte as the default format for hexdump. Also, skipping argument(s) does not affect the behavior of the following arguments.
In both exploit development and reverse engineering sessions, the contents of the stack is frequently investigated. By making the stack register default argument, we make the experience easier and faster. The same idea applies for the format argument of hexdump. Hexdump is usually used to see the bytes and dereference is used to see the dword/qword values stored. Also, position-independent arguments make the functions a lot easier to use.
Since the arguments are now position-independent, there …
=> Set position independent arguments with default values for hexdump and dereference

gef.py, tests/binaries/Makefile
Fixes #446 
Basically if you defined a structure with padding, the calculated/displayed offset wouldn't match the offset what the structure actually parses the value out of, size we just used the sum of the size of all of the previous fields, ignorant of padding.
=> pcustom: Correctly find field offset

gef.py
This patch highlights each vmmap entry based on its name/permissions.
- RX entries are colored with the `theme.address_code` setting
- RWX entries have an extra underline in the `Perm` column
- The heap entry is colored with `theme.address_heap`
- The stack entry is colored with `theme.address_stack`
The `context` command currently highlights various addresses based on its permissions and whether it points to the heap or stack. I think it would be relevant to have the same kind of highlighting for `vmmap` to improve readability.
| x86-32       | :heavy_check_mark:|
| x86-64       |:heavy_check_mark:||
| ARM          | :heavy_multiplication_x: | …
=> Add highlighting of vmmap entries based on permissions

gef.py
Just adds a single extra line to xinfo output with the offset from segment start; like we currently have for offset from page start. I find myself needing the offset from segments with pwntools more than the page offset.
| x86-32       | :heavy_check_mark: |                        | …
=> Add segment offset to xinfo

gef.py
- Selected thread number is highlighted with green
- Name is shown only if nor empty
- Added info about thread frame (PC and name)
Before:
After: 
| AARCH64      | :heavy_check_mark: |                        |
| `make tests` | :heavy_check_mark: |                        |
=> more threads info

gef.py
When I use `gef` to connect with `qemu-system-ppc -S -s` or `qemu-ppc -g 1234`, there will be an error because `QEMU` doesn't implement the `trap` register.
And the name provided to `parse_and_eval` is different from `read_register`.
(`gdb.parse_and_eval('$rax')` vs `gdb.selected_frame().read_register('rax')`)
That's to say that this `except` part is never executed correctly, and nobody complains this before.
So I simply return `None` with when we can't find the register and don't add check for this return value. I think it's enough.
| ARM …
=> Return None when read_register fails

docs/commands/functions.md, gef.py, tests/runtests.py
Instead of `$_pie()`, this adds `$_base()`, which, instead of an offset, takes an optional file name to match against.
Also fixes a bug where this function didn't work for remote targets, due to `vmmap`'s section names not matching the result of `get_filepath`.
There's a problem with how we split args that makes this weird to use in our own commands.
```
gef➤  x/s $_base()
0x400000:       "\177ELF\002\001\001"
gef➤  deref $_base()
0x0000000000400000│+0x0000:  jg 0x400047
0x0000000000400008│+0x0008:  add BYTE PTR [rax], al
0x0000000000400010│+0x0010:  add al, BYTE PTR [rax]
...
gef➤  deref $_base("libc")
0x00007ffff7a0d000│+0x0000: 0x03010102464c457f
0x00007ffff7a0d008│+0x0008: 0x0000000000000000
0x00007ffff7a0d010│+0x0010: 0x00000001003e0003
...
```
=> Base function

.github/PULL_REQUEST_TEMPLATE.md, gef.py
- Update the all_registers property
- include the 'a0' register
- rename the 'x4' register to the more common name 'tp'
- Fix the `syscall_instructions` property
| x86-32       | :heavy_multiplication_x: |                                          | …
=> riscv: minor updates to the riscv arch

gef.py
Hi @hugsy! First of all: thanks for your OSS involvement, beautiful and useful project, your volunteer effort is honestly appreciated.
Now. I've been using Gef to grease up debug of a **Linux kernel running under Aarch64 QEMU**. Mostly, works great, except this one little crash.
Pretty much every time I step into `hlist_add_head()` kernel function, `gef context` explodes trying to disassemble negative-something instructions. The traceback:
```
667		rest_init();
[ Legend: Modified register | Code | Heap | Stack | String ]
------------------------------------------------------------------------------------- registers ----
$x0  : 0x0000000000000000 -> 0x0000000000000000
$x1  : 0xffffffc01d84a080 -> 0x00008124f000000f -> 0x00008124f000000f
$x2  : 0x00000000000000d6 -> 0x00000000000000d6
$x3 …
```
=> Workaround a crash with negative nb_insn on ARM64

.travis.yml, tests/runtests.py
Following the news https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support, I've upgraded our old (and deleted) Travis-CI config. Currently it was setup for both `amd64` and `arm64`, but works only on x64 (the fault for arm64 is on Travis' side, not us). Currently in alpha on Travis, when it works, they announced they would extend to arm and powerpc: which would finally bring some CI for us on those platforms.
But for now, we can merge as it still provides a complementary CI check (on top of CircleCI).
| x86-32       | ✖️ | |
| x86-64       | ✔️  |                                           |
| ARM …
=> Return of Travis-CI

tests/runtests.py
The test is expecting the chunk to end up in the fastbins not in tcache, so disable it when running the test to keep things consistent.
```
======================================================================
FAIL: test_cmd_heap_bins_non_main (__main__.TestGefCommands)
----------------------------------------------------------------------
Traceback (most recent call last):
File "tests/runtests.py", line 197, in test_cmd_heap_bins_non_main
self.assertIn("size=0x20, flags=PREV_INUSE|NON_MAIN_ARENA", res)
AssertionError: 'size=0x20, flags=PREV_INUSE|NON_MAIN_ARENA' not found in 'Reading symbols from tests/binaries/heap-non-main.out...done.\nGEF for linux ready, type `gef\' to start, `gef config\' to configure\n80 commands loaded for GDB 8.
1.0.20180409-git using Python engine 3.6\n[+] …
```
=> disable tcache when running the test_cmd_heap_bins_non_main

gef.py
Libc filename regex now respects libc6_{version}.so format.
Sometimes libc.so file is called just libc.so.6 and we can't extract its version from filename, but we may try to look for it in wd path. …
=> Libc filename regex changed

gef.py
When the `syscall-args.path` setting is not configured, provide information that it can be installed using the gef-extras install script.
Also, the table output of `syscall-args` is not properly aligned. This is fixed here as well.
=> Improve output messages of syscall-arg command

docs/commands/context.md
Just a little change in the documentation of commands context
As said in this page, a section is hide when prepended by - ("To hide a section, simply use the context.layout setting, and prepend the section name with - or just omit it.").
So when running this command :
```
gef➤ gef config context.layout "-legend regs stack code args -source -threads -trace extra memory"
```
you will have no display of the legend section (or maybe have I missed something?)
You might have preferred to delete the "-" in the command instead adding "legend" to the ignored fields...
| x86-64 …
=> Simple doc fix

gef.py
https://github.com/hugsy/gef/issues/320#issuecomment-553081021 suggests a workaround for an inconsistenly named flag register on embedded ARM systems. (`$cpsr` vs. `$xPSR` vs. `$xpsr`) Unfortunately `$cpsr` was still hardcoded in this code which caused context to fail even with the workaround.
This patch just changes the code to use the `flag_register` field instead of an hard-coded value which in combination with the workaround linked earlier fixes gef on embedded ARM systems.
| x86-64       | :heavy_multiplication_x: | …
=> Fix context for embedded ARM workaround

Dockerfile, Makefile
Let's just make sure CI passes for this and that we can rebuild the docker image and run it locally.
=> Remove python2 from lint and docker image

gef.py
Sometimes libc may be called differently from "libc-x.xx.so" and in a similar way. For example, when using "ld" with "--library-path", it loads exactly "libc.so.6":
If it is not possible to find out the version of the libc from the name, we can try to look for the string "glibc X.XX" in the binary file. In tests on about 15 different versions (and for different architectures), this string was always present, unlike others.
After these changes, the library version was correctly defined (2.27 in my case) and I got the opportunity to work with the functionality for tcache.
Before:
After:
| x86-32       | …
=> Improved detection of libc version

gef.py
When using gef, when a chunk went to large bins it was not displayed as issued in #467 (and proposed correction) and #474 
| x86-32       | :heavy_multiplication_x: |            |
| SPARC …
=> Large bin not showing correction

gef.py
Tcache chunks formula has been updated. Now it respects chunk min size in ptmalloc2.
Same as in #464 
Tcache sizes are 0x10+ on 32bit, not 0x8+ since min chunk size is 16 (32 on 64bit)
| ARM          |  |                                           |
| AARCH64      |  |                                           |
| MIPS         |  |                                           |
| POWERPC      |  |                                           | …
=> Tcache chunks sizes miscalculated

Makefile
This way the correct make binary is going to be called.
GEF depends on gmake, which is not always available as
make. By using $(MAKE) we can make sure that this recursive
make invocation is going to use a proper make.
I stumbled upon this issue while porting GEF to FreeBSD.
| x86-32       | :heavy_multiplication_x: | N/A |
| x86-64       | :heavy_multiplication_x: |       N/A                                    |
| ARM          | :heavy_multiplication_x: |             N/A                              |
| AARCH64      | :heavy_multiplication_x: |              N/A                             | …
=> Use $(MAKE) instead of make

gef.py
For a gdb with LZMA supported, the return value of gdb.current_progspace().filename could be a string with prefix ".gnu_debugdata for target:", I add some codes to handle this case.
This patch is used to solve the issue https://github.com/hugsy/gef/issues/458
| AARCH64      | ✔️ |                                           | …
=> Patch the function get_filepath()

gef.py
This fixes a regression from commit 16aa313.
Assume these declarations in code:
uint32_t arr[16];
uint32_t a;
Before this fix, the following failed because content pointed by $sp
was shown instead:
memory watch arr
memory watch 0x404050
memory watch (void*)0x404050
memory watch &a
This commit also fixes this case (addr 0x404050 taken as size, $sp
used as address):
hexdump byte 0x404050
This commit also print usage when relevant (double address or double
size). …
=> Fix memory watch and hexdump confusing addr with size

gef.py
Currently when using gef with rust-gdb derefrencing fails as gef doesn't support Rust types. This patch adds support for Rust types much like the existing support for Golang.
Since certain gef commands use deference (e.g. pcustom), they also fail without this patch.
**Before**
Trying to deference when debugging rust binaries failed.
**Now**
Works nicely.
Against a x86_64 rust binary with rust-gdb.
| x86-32       | :heavy_multiplication_x: |                                            |
| ARM          | :heavy_multiplication_x: | …
=> Add dereference support for rust types

gef.py
This patch allows you to update gef with either --upgrade or --update passed as command line args, as I can never remember which one to use.
| x86-32       | :heavy_multiplication_x: |                                     |
| x86-64       |  :heavy_check_mark: |                                           | …
=> Add --upgrade as an alias to --update

gef.py
Fixes: DeprecationWarning: the imp module is deprecated in favour of
importlib; see the module's documentation for alternative uses.
I think this is equiv, but someone might want to double check. I just
ripped things off from here:
https://github.com/pyinvoke/invoke/pull/215/files
and tested a single codepath:
```
0:000   syscall-args
[+] Detected syscall exit_group
exit_group(int error_code)
[+] Parameter            Register             Value
error_code           $rdi                 0x0
```
| x86-32       | :heavy_multiplication_x: |                                           | …
=> Replace imp with importlib

gef.py
`help  stub` and `help set-permission` shows a python format string instead of the command name.
I've just added the missing `.format(_cmd_line_)`.
=> FIX missing command name in `help`

gef.py
This is a quick fix for an exception I was getting:
```
─────────────────────────────── Exception raised ───────────────────────────────
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
───────────────────────────── Detailed stacktrace ──────────────────────────────
↳ File "/home/nat/.gdbinit-gef.py", line 6298, in do_invoke()
→     addr = HeapBaseFunction.heap_base() + 0x10
↳ File "/home/nat/.gdbinit-gef.py", line 2403, in wrapper()
→     return f(*args, **kwargs)
↳ File "/home/nat/.gdbinit-gef.py", line 244, in wrapper()
→     return f(*args, **kwargs)
↳ File "/home/nat/.gdbinit-gef.py", line 3803, in invoke()
→     bufferize(self.do_invoke)(argv)
```
I didn't do any real testing, but I figured you might want it here.
=> Fix exception when the heap section is unavailable

gef.py
struct tcache_perthread_struct has changed after glibc2.30.
Before glibc2.30:
```
typedef struct tcache_perthread_struct
{
char counts[TCACHE_MAX_BINS];
tcache_entry *entries[TCACHE_MAX_BINS];
} tcache_perthread_struct;
```
After glibc2.30:
```
typedef struct tcache_perthread_struct
{
uint16_t counts[TCACHE_MAX_BINS];
tcache_entry *entries[TCACHE_MAX_BINS];
} tcache_perthread_struct;
```
- Finding counts of tcache bin should +16Bytes instead of +8Bytes.
- Finding the address of tcache bin[0] should change.
free(0x18) twice and free(0x28) once.
free(0x18) twice and free(0x28) once.
| Architecture | Yes/No                   | Comments                                  |
| x86-32       | …
=> Struct of tcache has changed after glibc2.30

gef.py
Fix #525. `hexdump` converts all its arguments to lower case, causing it to fail when a variable name (passed as the `ADDRESS` argument) contains uppercase letters (refer to issue for example).
Should be a quick one, anything I missed about keeping the case of `ADDRESS`?
| x86-32       | :heavy_multiplication_x: |         |
| x86-64       | :heavy_multiplication_x: |  :heavy_check_mark:   | …
=> hexdump: Do not convert ADDRESS argument to lower case

gef.py
glibc 2.32 will add support for protection of single-linked-lists such as the Fastbins and TCache lists. This support, which was [pushed](https://sourceware.org/git/?p=glibc.git;a=commit;h=a1a486d70ebcc47a686ff5846875eacad0940e41) already to glibc's master branch, is referred to us "Safe-Linking".
Safe-Linking masks the "fwd" pointers, and so this commit implements the support for unmasking ("reavel"ing) the pointers so they could be used properly by gef.
Note: Fixed my previous pull request so that the caller will explicitly pass True/False to specify if the "fwd" pointer is for a single-linked-list (SLL) or a double-linked-list which needs no unmasking.
| ------------ | :----------------------: | …
=> Support Safe-Linking in GlibC 2.32+

gef.py
I'm sorry. I'm not goot at using git, there's something wrong and I accidentally deleted the commit created before. So I created a new pr. …
=> fix potential bug in parsing tcache size

gef.py
Sometimes `clear_screen` commands deletes scrollback buffer which is annoying. So we make sure we don't do that since the command is set the default now
=> do not clear scrollback buffer

docs/commands/ida-interact.md, gef.py, scripts/ida_gef.py
This fixes up ida_gef.py to work with IDA > 7.2, while maintaining backwards compatibility.
| SPARC …
=> ida: Add IDA 7.2+ compatibility

gef.py
Clone of #469 
Parts of gef depend on or expects the file being debugged to be an ELF. This PR allows for the correct `current_arch` to be set as well as adding support for getting the memory mappings via `info mach-regions`.
As there have now been a few ctfs with mac pwns (eg [machbook](https://github.com/how2hack/my-ctf-challenges/tree/master/balsnctf-2019/machbook) and [applepie](https://github.com/david942j/ctf-writeups/tree/master/0ctf-quals-2019/applepie)) being able to use gef would be great.
| x86-32       | :heavy_check_mark: |       |
| x86-64       | :heavy_check_mark: |     also on macOS 10.15, gdb 8.3 …
=> Macho support

docs/commands/vmmap.md, gef.py
This was created to help identify which section an arbitrary address belongs to. This should help exploit developers quickly find which section a leak/random address belongs to. It was orginally a seperate command, but @hugsy suggested adding it to vmmap.
| x86-64       | :heavy_check_mark: |                                         | …
=> Add vmmap functionality

docs/commands/aliases.md, docs/commands/config.md, gef.py
Right now, gef stores its config file in the user's home directory, which can contribute a small amount of clutter. This one-line change allows a user to override the default location by setting the `GEF_RC` environment variable. Note, this specifies a path to the config file itself, not to the folder which contains it. The change is simple enough that I don't think it warrants the creation of any tests, though not sure.
| x86-32       | :heavy_multiplication_x: |                                      |
| ARM          | …
=> Allow location of config file to be user-defined via an environment variable

gef.py
When running GDB from virtual environment GDB always loads system's python so GEF can't load modules from the venv required to perform some GEF commands. This patch aims to provide a support for virtual environments so GEF is able to load modules from them. While it is mostly a GDB related problem I thought it would be nice to have this kind of feature in GEF since no other software I use really need such support for venvs.
| x86-32       | :heavy_multiplication_x: |                                    |
| ARM          | …
=> Add support for virtual environments

gef.py
There is a small typo in gef.py.
Should read `subtract` rather than `substract`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, substract -> subtract

gef.py
=> fix arch check for musl rust binaries

gef.py
I noticed that when we change the colour theme that the change isn't
picked up. It's because we don't clear the caches.
Instead of clearing ALL caches, we can just clear the cache of the
functions that read from the config, which luckily for us is (mostly)
just get_gef_setting.
=> Clear get_gef_setting cache when we write to __config__

gef.py
Don't clear the screen until we've built up the new context to print.
This should make the flicker better.
=> Context: Clear the screen only just before printing

gef.py
In some languages gdb prints the current endianness capitalized (e.g. "Little Endian").
To make this work with gef's `get_endian` function I added a conversion to lowercase letters.
| x86-32       | :heavy_multiplication_x: |                                |
| x86-64       | :heavy_check_mark: |       | …
=> made endianness check case insensitive

scripts/gef.sh
In a nutshell, I've enabled the `-L` flag on `curl` to follow redirects on `scripts/gef.sh` line 15. 
Manually.
```
$ cat script.sh
<snip>
curl --silent -L --output "${HOME}/.gef-${ref}.py" "https://github.com/hugsy/gef/raw/${branch}/gef.py"
<snip>
$ ls ~/.gef-60fd341ba076942faac96fd6118ca927998ec0d9.py
$ cat ~/.gef-60fd341ba076942faac96fd6118ca927998ec0d9.py
#
#
#######################################################################################
<snip>
GefAliases()
GefTmuxSetup()
```
I'm fairly unsure if you use some sort of lint for shell scripts (e.g. spellcheck) and I haven't used one. 
- [N/A] My code follows the code style of this project.
- [] My change includes a change to the documentation, if required.
- [] My change adds tests as appropriate.
LMK if this works.
=> Minor fix to allow redirects on installation script

tests/helpers.py
The error came from a `UnicodeDecodeError` when trying to decode the output from GDB.
I looked into the bytes that were being decoded, and realized it is `\xe2\x1b[H\x1b[2J\x94\x80`, which seems to be an ANSI character sequence `\x1b[H\x1b[2J` being inserted to the middle of a multibyte character `\xe2\x94\x80`, causing the decoding to fail at https://github.com/hugsy/gef/blob/d8cbb45c56c40bfe54d391423fe50d7811900c7e/tests/helpers.py#L31-L32
This is pretty weird. I wonder if it is a GEF problem, or a problem with `subprocess` buffering?
One option would be to remove such broken multibyte characters, since they don't impact the test cases, and I don't think they ever will. It would be a workaround for now to prevent the tests from failing.
```
lines = subprocess.check_output(command, …
```
=> Workaround to fix failing tests

gef.py
We were using `continue` in our loop trying to find an instruction boundary, but it was used in a nested loop making it completely useless!
This change uses `any` with a generator expression that keeps the break out of an inner loop, allowing the `continue` to work as expected.
=> Fix loop not breaking

tests/perf/context_times.sh
1. Fixes the script looking for the binary in the _binaries_ directory.
2. Fixes some formatting.
3. Runs the test 5 times to get a more consistent average.
=> Update context_time.sh to run 5 times

gef.py, tests/perf/context_times.sh
Aggressively cache functions.
Use `lru_cache` a lot more. I noticed that we spent most of our time calling `get_register`, `gef_disassemble`, and `dereference`.
For example, on EACH line of the stack context we get the value of each register, but obviously this shouldn't change within one one context. So let's cache.
The risk here is that we get stale values, but I (hopefully) remediate this by clearing the cache more often: I hook reg changed and mem changed events and clear all caches in that case.
This offers HUGE per improvements:
with:
```
1    0.000    0.000    0.008    0.008 profile:0(gdb.execute('context'))
```
Granted, this is with a 'hot' cache.  If I clear the caches first I get a more reasonable speedup:
```
1    0.000    0.000    0.026    0.026 …
```
=> Cache more functions

.github/ISSUE_TEMPLATE/bug_report.md
Update the issue template so that the 'hints' are in comments since no one deletes them.
=> Update issue template to use comments

gef.py
Caching the results of `get_main_arena` resulted in inconsistent data
when trying to print fastbins from non-main arenas. If the user printed
fastbin lists in the main arena, then switched to a different arena and
printed fastbin lists, gef would show output from the main arena rather
than the new arena because `get_main_arena` would return a cached
result.
**Before**
**After**
Only tested on x86-64, but should be architecture agnostic. Used the `heap-non-main-arena.out` binary for testing (disabling the tcache in order to focus on fastbin results).
| x86-64       | …
=> Remove caching from get_main_arena

gef.py
Since we don't use python2 we should be able to clean up the super calls.
Also, we don't lint bad super calls so we can remove the pylint comment.
=> Use python3-style super() calls

scripts/gef-extras.sh
Moves the `~/gef-extras` folder to `~/.config/gef-extras` if it exists, or to `~/.gef-extras` otherwise. This will help de-clutter the home folder. The gef installer already does this but the gef-extras installer does not.
I ran several tests with different `$HOME` values to verify that the installer still works.
=> Fix gef-extras directory location

gef.py
This PR slightly improves #579: instead of hardcoding some addresses which would not work on non 64b archs, we completely assumes that the debugged binary is emulated by qemu and therefore show the qemu mem maping. This allows for a clean and effective way to have the correct page permissions set in gef (and might help oneself who tries to escape the qemu process 😃 )
The reasoning behind is mostly that when debugging we don't really care that it's qemu-emulated, and have a proper memory mapping is just that much more useful info.
Before
After
| x86-64       | …
=> Qemu-user mmap support

docs/commands/heap.md, gef.py, tests/binaries/Makefile, tests/binaries/heap-tcache.c, tests/runtests.py
Closes #634 
| x86-32       | :heavy_multiplication_x: |                                      |
| …
=> Upgrade tcache

docs/commands/name-break.md, docs/commands/pcustom.md, docs/commands/print-format.md, docs/commands/search-pattern.md, docs/commands/syscall-args.md
Scope of change is restricted to docs only.
Corrected several typos in markdown documents.
Tests n/a. Corrections match Standard English. Second set of eyes suggested.
| POWERPC …
=> fix(docs): corrects common typos in various documentation files

gef.py
Firmware execution may start at address `0x0`. Disassembling instruction before addresses near `0x0` leads to an address underflow and therefore an `gdb.MemoryError` exception during `context`.
NOTE: An unmapped page may still be reached with the unchecked `addr - n * instruction_length` location calculation, so maybe removing the special case for fixed-sized ABI's may be the better solution.
unfixed:
fixed:
| ARM          | :heavy_multiplication_x: | …
=> Fix address underflow on disassemble (Fixed-length ABI)

gef.py
Fix failure `[!] Command 'context' failed to execute properly, reason:` while estimating aarch64 test/compare and branch instructions.
| AARCH64      | :heavy_check_mark: | tbz, tbnz, cbz and cbnz branches are correctly estimated| …
=> Fix aarch64 tbz, tbnz, cbz and cbnz instructions estimation

docs/commands.md, docs/commands/aliases.md, gef.py, tests/runtests.py
Adds better functionality to the `aliases` command. This closes Issue #636. Examples below.
Adding an alias... (command can contain spaces)
```
aliases add [alias] [command]
```
Removing an alias...
```
aliases rm [alias]
```
Listing aliases...
```
aliases list
```
Any aliases added will be automatically added to the `~/.gef.rc` file, and the removed aliases will be removed. I have also updated the docs with the new usage of the command.
I have tested this patch across several machines running Debian and Arch based distros.
=> Better GEF Aliases Functionality

docs/api.md, gef.py, tests/runtests.py
Use `argparse` module to provide a lightweight way to parse command line arguments, instead of the hackish `getopt` we used so far.
This PR adds a new decorator, `@parse_arguments()` that takes 2 arguments: a `dict` of the required arguments, and another of optional non-positional arguments. Items of those `dict`s have the format `{ "argument_name" : default_value }`: the type expected is inferred from the default value (therefore avoid using `None`, for strings prefer `""`, for ints prefer `0`, etc.)
Positional (required) arguments also allow to pass a list of default values:
```python
@parse_arguments({"foo": ["bar", "baz"]}, {"--plop": 1})
def do_invoke()...
```
Note that the argparsing is optional, *but* if we use it we must change the signature of the decorated `do_invoke`. Doing so …
=> Proper command argument parsing

gef.py
Restore selected frame after switching threads in context_threads.  …
=> Restore selected frame after context_threads

gef.py
- Removed `@lru_cache` for `gef_disassemble` since it returns generator and repetitive `context_code` shows empty code
- Added `get_register_for_selected_frame` to correctly cache register values depending on selected frame.
| …
=> Fix incorrect lru_cache usage

gef.py
Context registers order was broken
Now it is fixed
| …
=> Fix context registers order

.github/workflows/run-tests.yml, gef.py
=> Remove more python2-specific stuff

gef.py, tests/runtests.py
```
x86-64: Preserve RCX and R11 when calling mprotect_asm (syscall)
On x86-64, the syscall instruction will clobber RCX and R11. It uses
RCX to save the return address and uses R11 to save the RFLAGS.
This means we will lose our old RCX and R11 value after the syscall
returns to userspace.
Bug reproduction steps (see how RCX and R11 change):
$ gdb any-program
starti
p $rcx=0
p $r11=0
set-permission $sp
p $rcx
p $r11
This commit fixes the bug by preserving RCX and R11.
Signed-off-by: Ammar Faizi <ammarfaizi2@gmail.com>
```
| x86-32       | :heavy_multiplication_x: |                                           |
| …
=> x86-64: Preserve RCX and R11 when calling mprotect_asm (syscall)

gef.py, tests/runtests.py
```
Komori Kuzuyu <komori.kzy@gmail.com> wrote:
> search-pattern command stop finding string pattern after error "Cannot
> access memory at address xxxxxxxxxxxx". Checking /proc/$pid/maps the
> address mentioned in error is readable but cannot be read from gdb.
>
> The memory is a mapped file to /dev/dri/renderD128
>
Do not assume virtual memory that has read bit is always directly
readable from userspace. We have a special case where /proc/$pid/maps
shows virtual memory address with a read bit, but it cannot be read from
the GDB.
This commit adds an exception handler for read_memory on search-pattern
command when such a special case occurs.
Before this commit, the search-pattern command stops when it meets the
above case (unhandled exception).
After this commit, the search-pattern …
```
=> search-pattern: Don't stop searching when read_memory fails

docs/commands/dereference.md, gef.py
This patch allows to set a different base address for offset calculation for the `dereference` command while not breaking previous usage. This allows quicker identification of relevant memory addresses in some cases. A common use case is using `ebp`/`rbp` as a reference on the stack in `x86` architecture (see e.g the very old issue #67): That way `gef`s `dereference` command output can e.g. be compared easier to most, if not all, disassembler and decompiler outputs for stack variables.
This is how the new usage looks like:
```sh
gef> dereference $rsp l7 r$rbp
0x00007ffe6ddaa3e0│-0x0030: 0x0000000000000000    ← $rsp
0x00007ffe6ddaa3e8│-0x0028: 0x0000000000400970  →  <__libc_csu_init+0> push r15
0x00007ffe6ddaa3f0│-0x0020: 0x0000000000000000
0x00007ffe6ddaa3f8│-0x0018: 0x00000000004006e0  → …
```
=> deref: added option to use reference address for offset calculation

docs/index.md, gef.py
Changes `which("python")` to `which("python3")` in the `UnicornEmulateCommand`.
This is required on some Distros to work correctly.
| x86-32       | :heavy_multiplication_x: |                                  |
| x86-64       | :heavy_check_mark: |  quick manual testing       | …
=> fix python executable version in unicorn-emulate

docs/commands/hexdump.md, gef.py, tests/runtests.py
see #681
`memory watch` now uses the new argparse syntax of `hexdump`. Also fixed related `hexdump` usage instructions and documentation and added test to check for exceptions with the `memory` commands.
| x86-32       |:heavy_check_mark:  |  |
| x86-64       |:heavy_check_mark: |                                           | …
=> Fixed: `memory watch` uses new argparse syntax of `hexdump` cmd

docs/commands/version.md, gef.py, mkdocs.yml
=> Add git blob hash to `version` cmd

gef.py, tests/binaries/memwatch.c, tests/runtests.py
see  #687
This is an idea for `memory watch` unit tests that check the actual content of the memory.  The `memwatch.c` file could also be used to unit test memory for other commands such as `deref` and `hexdump`. It reads in an integer from stdin to a global variable. Before and after the write breakpoints are hardcoded as assembly instructions for convenience. The first one e.g. while setting the unit test up and the second one to check the result of the write.
I added two tests: 
1. write `0xdeadbeef` and check for it at the variables memory address (and check that `0xcafebabe` is not found)
2. write `0xcafebabe` and check for it at the variables memory address (and check that `0xdeadbeef` is not found)
| Architecture |          Yes/No          | Comments …
=> memory watch unit tests for checking memory content

gef.py
see #646
We probably should add tests that make sure ignoring some members of the heap arena does not cause other issues. This should be done before merging. 
Also the now displayed error message might not be the best? It is
```bash
[!] Glibc arena: There is no member named next_free.
``` …
=> Fix heap commands when the glibc arena has not set all expected members

docs/commands/heap.md, gef.py
see #689
I added some comments and references, renamed the `address` variables to `data_address` and `base_address` to be more concise (at least imo) and mimicked the behavior of glibc (before and since version 2.26) to calculate `MALLOC_ALIGNMENT` and then used that to re-align the `data_address` of the chunk.
| x86-32       | :heavy_check_mark: |      |
| MIPS …
=> Mimic glibc's MALLOC_ALIGNMENT for heap chunks

scripts/gef.sh
Fixing errors when running on Ubuntu 21.04:
* test: unexpected operator
* curl: not found
| SPARC …
=> gef.sh is now works on Ubuntu 21.04 (Hirsute Hippo) #699

docs/commands/capstone-disassemble.md, gef.py, tests/runtests.py
As part of #693 this PR fixes the documentation and help messages for the `capstone-disassemble` command. Furthermore  the command was not working in use cases like emulating aarch64 inside qemu. This was due to an uncaught exception caused in `gef_get_auxiliary_values` when gdb's `info auxv` doesn't return useful results. This bug has been fixed. Also resolving of `LOCATION`s has been fixed.
With this PR I also propose changing the syntax for the `location` argument back to how it was before argparse: as a positional argument.
During this PR I introduced a new convenience wrapper function around gdb's `parse_and_eval` to specifically resolve `LOCATION`s. This way other commands can rely on it without having to handle the different possible cases neccessary (because e.g. gdb resolves …
=> Fix capstone-disassemble command and documentation

docs/commands/name-break.md, docs/commands/pie.md, gef.py
This PR is part of #693 and covers the following points:
- Fix address parsing for `name-break` cmd by using `parse_address()` now.
- Update `name-break` docs.
- Rename "location" argument to "address".
- Clarify that `pie breakpoint` takes an offset (or symbol) as an argument and not an absolute address.
- Fix address parsing for `pie breakpoint`.
- Update `pie` commands documentation and usage instructions.
| ARM          | :heavy_multiplication_x: | …
=> Update break commands

gef.py, tests/runtests.py
see #707
My proposed solution is to move the address parsing to `NamedBreakpoint` so the original user input will be displayed when hitting the breakpoint but the location will be converted to an address and given to GDBs `Breakpoint` as a string with a prefixed `*`. 
I also added a test (which was missing previously) to check if the `name-break` command throws an exception.
| AARCH64      | …
=> Fix name-break address parsing (#707)

gef.py, tests/runtests.py
fix #707
Using `parse_address`, when the user already specified a direct address like `*0x40600` will result in dereferencing the address instead of just passing it to `Breakpoint`.
This patch replaces the default value for address, if none is given, with `*$pc` instead of `$pc` and removes parsing of the address completely, since user input will already be in the correct format for `Breakpoint`.
This way `nb` behaves more like default `b` command again
```
gef➤  nb testpc
Breakpoint 1 at 0x7ffff7ebde82: file ../sysdeps/unix/sysv/linux/read.c, line 26.
gef➤  nb testdirect *0x7ffff7ebde8a
Breakpoint 2 at 0x7ffff7ebde8a: file ../sysdeps/unix/sysv/linux/read.c, line 26.
gef➤  nb testdirect *0x7ffff7ebde8a+4
Breakpoint 3 at 0x7ffff7ebde8e: file ../sysdeps/unix/sysv/linux/read.c, line 26.
gef➤ …
```
=> Fix namebreak and add additional unit tests

docs/commands/elf-info.md, docs/commands/heap-analysis-helper.md, docs/commands/help.md, docs/commands/hexdump.md, docs/commands/process-search.md, docs/commands/process-status.md, docs/commands/registers.md, docs/commands/scan.md, docs/commands/set-permission.md, docs/commands/tmux-setup.md, docs/commands/version.md, gef.py
This PR is part of #693 and covers the following points:
- Update docs for `elf-info` command.
- Update docs for `hexdump` command.
- Update docs for `gef help` command.
- Update docs for `process-status` command.
- Update docs for `process-search` command.
- Update help msg for `process-search`.
- Update docs for `registers` command to include filtering capabilities.
- Display error message for invalid registers when running `registers` command.
- Change 'small' to 'little' (endian) in search-pattern cmd.
- Update docs for `tmux-setup` command to include a note on possible tmux color issues on Linux.
- Update docs and help msg for `set-permission` command to include permission usage instructions.
- Update docs for `scan` command.
- Update docs for `process-search` command to include note …
=> Update docs for several commands

docs/commands/heap.md, gef.py, tests/binaries/heap-fastbins.c, tests/runtests.py
This PR is part of #693 and covers the following points:
- Add the missing `set-arena` subcommand to the `heap` help message.
- Fix address parsing for `heap chunks` command from a simple conversion to `int` to use `parse_address()` instead.
- Update `heap bins fast` command output in documentation.
- Fix `test_cmd_heap_bins_fast` test to actually look for a fastbin in the output. To do this the `heap-fastbins.c` had to be changed to first fill all 7 tcache bins before freeing the actual fastbin to look for.
EDIT: `heap-fastbins.c` doesn't need to be udpated when disabling tcache via the environment in GDB: `set environment GLIBC_TUNABLES glibc.malloc.tcache_count=0` (as pointed out to me by @irontigran )
| Architecture |          Yes/No          | Comments …
=> Update and fix heap command

.github/workflows/run-tests.yml, tests/runtests.py
Adding `test_cmd_gef_remote` (Continuation of #685 and #686).
Currently "only" testing `vmmap` in the gef-remote session as it is important for GEF to get the process mapping right in such remote sessions. But other commands can easily be added if/when needed the same way. …
=> Add test for gef-remote cmd

gef.py
Patches a check that (though uncommented) appears to have been introduced to compensate for the `have_fastchunks` flag being moved from an arena's `flags` into its own field in GLIBC 2.27. The code in question is used to parse arenas when the linked GLIBC build has no debug symbols available. The only thing I've changed is the version number, it should read >= 2.27 rather that 2.26. In its current state, if you try to debug a program linked to a GLIBC 2.26 build without debug symbols, the arena layout is misinterpreted and heap commands will hang or give incorrect information.
Only tested on x86_64 hardware.
=> Correct have_fastchunks arena adjustment

docs/commands/unicorn-emulate.md, gef.py, tests/runtests.py
This PR is part of #693 and covers the following points:
- Fix emulating the wrong number of instructions for even numbers
- Update docs for cmd (incl Screenshot)
- Fix alignment of registers in output
- Fix address parsing of cmd
- Update test to check for failed emulations and count the number of emulated instructions
Here some before/after screenshots:
In the future it might even be cool to print the registers in GEFs standard way (incl marking tainted registers with color) but this PR was more about fixing the broken parts of the command.
| x86-64       | …
=> Fix unicorn-emulate cmd

gef.py
see #706 
This PR adds the capability to `GlibcArena` to get the  base address of the associated heap region  for main_arena and also non-main arenas. This new heap base address is used in the `heap chunks` command to make it work with non-main arenas.
For now better tests that check if `heap chunks` works with "main_arena" but also a "non-main arena" are still missing in this PR.
| AARCH64      | …
=> Fix 'heap chunks' command for non-main arenas (#706)

.github/workflows/run-tests.yml, Makefile, README.md, requirements.txt, tests/binaries/unicorn.c, tests/runtests.py
This PR is background work for the self-hosting CI runners that will allow to test non-x86 archs (although GH Actions only offers ARM & AARCH64 for now).
Since each unittest we do is totally independent from one another, we can massively improve the time ~~wasted~~ spent in CI testing by splitting on more cores. That's exactly the point of this PR: make use of `pytest` + `pytest-xdist` on top of `unittest` to distribute the tests. New test time is (roughly) the old divided by the number of cores given.
| x86-32       |  :heavy_check_mark: | | …
=> Use `pytest` on top of `unittest` to allow multi-proc execution

gef.py
Fix error of
```bash
[ Legend: Modified register | Code | Heap | Stack | String ]
[!] Command 'context' failed to execute properly, reason: argument of type 'NoneType' is not iterable
```
when breakpoints are set and breakpoint.location is not available.
| x86-32       | :heavy_multiplication_x: |                                           |
| x86-64       |           Yes            |                                           | …
=> Fix context failed to execute because breakpoint.location is None

gef.py
As part of #693 this tiny PR removes the GEF error messages on `-h`/`--help` for the commands. …
=> Fix error message on help

docs/commands/heap.md, gef.py, tests/runtests.py
see #706, #709 and #711
This PR fixes the `heap chunks` command for arenas with multiple heaps as described by @irontigran. The tests in #711 do work with this PR after fixing an error in it (when the `before` cmds are executed the heap has not been initialized yet).
There are quite some chunks here so I added a screenshot of the beginning and the end of the command output:
| AARCH64      | …
=> Fix heap chunks cmd for multiple heaps per arena

.github/stale.yml
Created `.github/stale.yml` to auto tag an inactive issue, and close it if still no activity; as recommended by @daniellimws [here](https://discord.com/channels/705160148813086841/705160148813086843/836055917233176577)
Pretty straight forward, but you can read https://github.com/marketplace/stale for details.
This is the default configuration (I just made the `daysUntilClose` to close after 30), with custom comments. 
Note: The file must be merged in `master` to be effective.This
=> Configuration for the stale bot 

tests/binaries/Makefile, tests/binaries/heap-multiple-heaps.c, tests/runtests.py
This test checks that when a non-main arena has multiple (and therefore
non-contiguous) heaps, we still print them all out.
As part of the ongoing effort to fix the `heap chunks` for non-main arenas, this PR adds a test that triggers the creation of a new heap in a non-main arena. This new heap will be non-contiguous with the original heap, which is a corner case that our eventual solution for the `heap chunks` command will have to handle.
Originally discussed at #709. …
=> Add test for printing chunks with multiple heaps

docs/commands/heap.md, gef.py, tests/runtests.py
This PR adds a new flag `--all`/`-a` to the `heap chunks` command to print out all chunks of all arenas at once (see Screenshot).
Furthermore the style of the Arena output is adjusted to match the style of the Chunks:
- The word "Arena" is colorized (blue).
- The whitespace right after "Arena" has been removed.
| MIPS …
=> Add feature to print heap chunks of all arenas

gef.py
This small refactoring PR replaces the following occurrences with `parse_address` for consistency and easier maintainability:
- `to_unsigned_long(gdb.parse_and_eval(...))`
- `int(gdb.parse_and_eval(...))` …
=> refactor: use parse_address whenever appropriate

Makefile, tests/helpers.py, tests/runtests.py
We were absolutely falling for the mutable default pitfall: When we called functions such as `gdb_run_cmd` without `before` set, we were tacking on extra commands each time! That's what linters are for!
=> CI: Lint: Add more linters to test files

docs/api.md, docs/commands/context.md, gef.py
This patch adds a new external api: `register_external_context_pane`, which takes three parameters:
1. `pane_name`: str. The name that will be printed as the context panes title
2. `pane_function`: function. The function that will be called to display things after the context title. Should use gef_print.
3. `pane_title_function`: function. The function returns a string which will be used for the context pane title.
To be concise, this new api essentially allows you to pass it an arbitrary function that will be executed after displaying your new context's title. More things could be added to create a wrapper class, but overall this is good enough to allow users to display arbitrary text on each break event while living in the context command. 
This patch will make the world better because …
=> Support for custom contexts in ContextCommand

docs/api.md, gef.py
To allow a user to implement a custom context pane we need to give them a way to print no title. This includes removing the entire title line so nothing looks off. Currently, if you return `""` from the user function, which is handled with `context_title`, then you get an empty title line. We should have support for both an empty title line and the absence of one. I purpose we allow the user to return `None` and modify the `context_title` function slightly. 
| ARM          | …
=> Allow empty context titles

gef.py
I noticed that `GEF` didn't close some of the files it opens and this PR should remedy this. …
=> fix: cleanly close opened files

gef.py
see Issue #735 
| RISC-V       | :heavy_multiplication_x: | …
=> fix: DeprecationWarning for unicode-escape decoding

docs/commands/heap.md, gef.py, tests/runtests.py
add a number argument for heap chunk command which is usable for statically linked binary. There is no need to know the main_arena address and mp_ address for heap chunks, just chunk address and number.
```
gef➤  heap chunk -h
usage: heap chunk [-h] [--allow-unaligned] [--number NUMBER] [address]
positional arguments:
address
optional arguments:
-h, --help         show this help message and exit
--allow-unaligned
--number NUMBER
gef➤  heap chunk 0x4e5400
Chunk(addr=0x4e5400, size=0xd0, flags=PREV_INUSE)
Chunk size: 208 (0xd0)
Usable size: 200 (0xc8)
Previous chunk size: 0 (0x0)
PREV_INUSE flag: On
IS_MMAPPED flag: Off
NON_MAIN_ARENA flag: Off
gef➤  heap chunk --number 6 0x4e5400
Chunk(addr=0x4e5400, size=0xd0, flags=PREV_INUSE)
Chunk(addr=0x4e54d0, size=0x1a0, flags=PREV_INUSE) …
```
=> add number arg for 'heap chunk' command

gef.py
Switches to using hashlib.sha256 instead of hashlib.sha1 for the gef_hash.
This is primarily to quiet static analyzers that complain about the use of SHA1.
=> Use sha256 for gef_hash to quiet static analyzers

gef.py
`assert` are bad, so we remove one here, and give a second chance for `get_register` to execute properly if/when register doesn't start with a `$` (like PPC or MIPS at least).
Register names don't always start with `$` (sometimes nothing - MIPS/PPC, something `$` - x64, sometimes `%` - SPARC).
This PR allows `get_register` to still attempt to get the value using `Frame.read_register()` even if the register doesn't start with `$`.
This PR should fix #752
| x86-32       | :heavy_check_mark: |  | using `make test` 
| ARM          | …
=> Remove the `assert` on `get_register`

gef.py
This  small PR simplifies a tiny block of code in `print_guessed_arguments` that seems to be resulting in some cases in an TypeError excetion as described in #753.
Fixes #753 
| x86-32       | :heavy_check_mark: | Using `make test`  |
| POWERPC      | :heavy_multiplication_x: …
=> Simplify how `nb_argument` is calculated in `print_guessed_arguments`

gef.py
This PR removes the last `assert` in `GlibcHeapTcachebinsCommand.tcachebin()`. …
=> Remove final `assert`

gef.py
Trivial PR to add the constants for M68K to `gef` so it can be sourced from https://github.com/hugsy/gef-extras/blob/master/archs/m68k.py
| SPARC …
=> Adds constants to `gef.py` for M68K support (in `gef-extras`)

scripts/gef.sh
this patch fixes an error with bash processing the install script so that it actually runs.
this is related to the installation script which creates the following error on ubuntu 20.04:
```
~ $ bash -c "$(wget http://gef.blah.cat/sh -O -)"
--2021-12-06 23:22:48--  http://gef.blah.cat/sh
Resolving gef.blah.cat (gef.blah.cat)... 40.121.232.30
Connecting to gef.blah.cat (gef.blah.cat)|40.121.232.30|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/hugsy/gef/raw/master/scripts/gef.sh [following]
--2021-12-06 23:22:48--  https://github.com/hugsy/gef/raw/master/scripts/gef.sh
Resolving github.com (github.com)... 140.82.113.4
Connecting to github.com (github.com)|140.82.113.4|:443... connected.
HTTP request sent, awaiting response... 302 …
```
=> fix bash errs on unary operator expected

gef.py
This refactoring PR addresses 3 different PEPs:
- [PEP 274 - Dict Comprehensions](https://www.python.org/dev/peps/pep-0274/) (Python 2.7 + 3.0): This PR uses the dict comprehension syntax where appropriate.
- [PEP 289 - Generator Expressions](https://www.python.org/dev/peps/pep-0289/) (Python 2.4): This PR replaces list comprehensions with Generator Expressions where appropriate for better memory efficiency.
- [PEP 380 - Syntax for Delegating to a Subgenerator](https://www.python.org/dev/peps/pep-0380/) (Python 3.3): This PR uses the `yield from` syntax.
| x86-64       | …
=> Refactor: Generators and Comprehension

gef.py
As Part of [PEP 3151](https://www.python.org/dev/peps/pep-3151/) (Python3.3) several error classes have been merged into `OSError` and have then been aliased to `OSError`. This PR replaces the aliases.
| x86-32       | :heavy_check_mark: | | …
=> refactor: replace OSError aliases

gef.py
As Part of [PEP 3210](https://www.python.org/dev/peps/pep-3120/) in Python 3.0 the utf-8 encoding declaration is the default and can be omitted (which saves some bytes for the whole file ;) )
| x86-32       | :heavy_check_mark: | | …
=> refactor: remove utf8 encoding declaration

gef.py
This huge PR adds type hints to the gdb8/py36 refactor branch and thereby reveals some logical bugs that can be addressed moving forward.
(Probably this PR does not cover 100% of the places where python 3.6. typing hints could be added but I wanted to push it already because I'm not sure about my schedule these next days) …
=> refactor: add type hints

gef.py
This PR replaces all `.format(...)` and `%` strings with f-strings. …
=> refactor: use f-strings across codebase

tests/binaries/Makefile, tests/binaries/heap-bins.c, tests/runtests.py
This PR adds some missing tests for:
- `heap bins small`
- `heap bins large`
- `heap bins unsorted`
All 3 new tests use the same binary file `heap-bins.out`. …
=> tests: add tests for heap bins small, large and unsorted cmd

tests/runtests.py
Noticed this test was passing before I got keystone working in my docker image.
=> tests: keystone assemble test should fail without the package

gef.py
The new API for changing settings configs in GEF has broken the `add_context_pane` API. This is an update for that. …
=> updated add_context_pane settings use

docs/commands.md, docs/commands/assemble.md, docs/commands/checksec.md, docs/commands/heap-analysis-helper.md, docs/commands/heap.md, docs/commands/stub.md, docs/commands/syscall-args.md, docs/commands/trace-run.md, docs/commands/vmmap.md, docs/commands/xfiles.md, docs/faq.md, gef.py
I tested all the links. A surprising number don't have correct certs for their domains or don't host on https at all. I didn't change those links.
=> Use https URLs where we can

gef.py
Simple PR to allow `@deprecated` warning display to be toggled off via config. …
=> `@deprecated` warning display can be toggled off

gef.py
This PR adds still missing type hints to `gef.py` (Issue #787).
Also a few very minor type hint related issues have been fixed (e.g. removing `return <expression>` where expression always evaluates to `None`)
EDIT:
The PR also removes a few unnecessary function/method arguments …
=> refactor: add missing py3.6 type hints

gef.py
* Make `gef_print` take variadic arguments like `print` does.
* Make `gef_print` not return anything like `print` does
* Make `warn`, `info`, etc. not return anything since `gef_print` doesn't.
* Cleanup some formatting/prints.
Closes #788
=> Variadic gef print

gef.py, tests/binaries/pcustom.c, tests/runtests.py
This PR is a complete rewrite of the `pcustom` command (and all its subcommands). It creates and uses a new `ExternalStructureLoader` class that efficiently allows to manipulate custom `ctypes.Structures` located in `gef.config["pcustom.struct_path"]`.
On top of being way more Pythonic, the great advantage of this approach is that now *any* command/function can use those new imported types, which is much more preferable to the old approach. 
This is a first step towards what was described in #778 …
=> Complete rewrite of `pcustom` command

gef.py, tests/runtests.py
Bringing some more Python3.6 joy to the `Elf`  class and subclass, also benefiting the type hinting, which allows to delete ~100 loc of string printing. Some details:
- Introduce new classes derived from `enum.Enum` or `enum.Flag` in the `Elf`, `Phdr` and `Shdr` classes
- `get_entry_point` can now be deprecated in favor of `gef.binary.entry_point`
- Simplified the helpers (`is_arch`, `is_x86_*`) which are way faster now (one lookup and test vs `gdb.execute`)
- renamed `set_arch` to `reset_architecture` (doesn't return, the result was never used anyway)
- we make `Elf` raise if the binary is corrupted (i.e. bad magic), any GDB won't process it
- The old format of `Elf.$arch : int` was kept but deprecated (since they are property we can't use the decorator, so if you have ideas 😄 )
| …
=> ELF class upgrades

gef.py, tests/runtests.py
fixes #785
| RISC-V       | :heavy_multiplication_x: | …
=> fix: heap bins commands

gef.py
Dropping this was causing 30-40% performance degradation of our
'context' use case. We already add the 'hash_key' so that the LRU cache
takes into account the selected frame to avoid using the cache when the
frame has changed. …
=> Re-add lru_cache to __get_register_for_selected_frame

scripts/gef-extras.sh
I tried to install `gef-extras` using `scripts/gef-extras.sh`, but I got the following error:
```
GEF for linux ready, type `gef' to start, `gef config' to configure
96 commands loaded for GDB 9.2 using Python engine 3.8
[!] Invalid command format
[!] Invalid command format
[+] Configuration saved to '/home/daniel/.gef.rc'
```
I changed the config paramter names according to the [README](https://github.com/hugsy/gef-extras/blob/master/README.md) of gef-extras, which fixes the installation for me. It leads to the following result:
```
GEF for linux ready, type `gef' to start, `gef config' to configure
96 commands loaded for GDB 9.2 using Python engine 3.8
[+] Configuration saved to '/home/daniel/.gef.rc'
```
| Architecture |          Yes/No          | Comments …
=> Update gef config parameters of gef-extras installation script

scripts/gef-extras.sh, scripts/gef.sh, scripts/generate-api-docs.sh, tests/perf/context_times.sh, tests/run-remote.sh
Some Operating Systems like OpenBSD, Solaris or NixOS have a different path for `bash`. This PR makes the shell scripts more portable across these systems by changing the shebang lines to:
```sh
#!/usr/bin/env bash
```
https://en.wikipedia.org/w/index.php?title=Shebang_(Unix)&oldid=878552871#Portability
=> fix: make shebang lines portable

gef.py
Simple PR
Type hinting revealed a bug in the way we loaded external plugins: `register_external_command` was receiving an instance of a class for each new external script. This lead to a double initialization when calling `gef.gdb.load(cls)`. 
It was fixed by registering directly a class (just like we do for `register_command`). The `gef-extras` plugins were also updated.
| `make test`  | :heavy_check_mark: |                                           |
=> Fix double loading of external plugins

gef.py
During the code refactoring `libc_args_definitions` was mistakenly replaced to point to `gef.ui.highlight_table`, resulting in issues like #820 
This PR fixes it by creating a proper table in the `gef` namespace `gef.ui.libc_args_table` ; and make the old  `libc_args_definitions` dict point to `gef.ui.libc_args_table`
Fixes #820  …
=> Convert `libc_args_definitions` to `gef.ui.libc_args_table`

docs/commands/pcustom.md, gef.py
This feature was suggested by a friend of mine and it's pretty simple and cool: the idea is to allow GEF to not just support static `ctypes.Structure` based classes for `pcustom`, but also methods that would act as class factory. Even though we lose a bit in the structure readability (IMO) we gain tons in fine tuning of the generated class, thanks to the runtime info provided by GEF.
For example it means we can merge the `elf` structure defined [here for 32b](https://github.com/hugsy/gef-extras/blob/dev/structs/elf32_t.py) and [there for 64b](https://github.com/hugsy/gef-extras/blob/dev/structs/elf64_t.py) or also improve the currently incorrect structure definition of the heap chunks/arenas in `gef-extras` based on the libc version.  I've also added a simple example in the docs.
| …
=> Add class factory support for `pcustom`

gef.py
Removing unnecessary warning when using gef with gef-extras.
This PR solves issue related to [https://github.com/hugsy/gef/issues/823](https://github.com/hugsy/gef/issues/823) .
Fixes #823
=> remove unnecessary warnings

docs/api.md, gef.py
~~Should help with #799. Contains an enhancement for `get_arch()` and uses that function to determine whether we're dealing with ARM-M if the architecture has been added by gef-extras.~~
Add a callback to `Architecture` which can be used to detect whether a architecture supports a specific gdb arch.
| ARM          | :heavy_check_mark:  |                                           | …
=>  Add mechanism to let architectures specify whether they support a gdb arch

docs/commands/gef.md, gef.py, tests/commands/gef.py
Simple new command for `gef` to install `gef-extras` scripts individually directly from inside `gef`.
Docs & tests added (I used this opportunity to complete some missing tests as pointed out [here](https://github.com/hugsy/gef/pull/813/files#r805348942)
| x86-32       | :heavy_check_mark: | Replace with :: if tested |
| ARM          | :heavy_check_mark: |                                           | …
=> New subcommand `gef install`

gef.py
This update is to improve detection of Stack Canaries in cases where the symbol is located in one of the relocation sections. 
| x86-32       | :heavy_check_mark:  |                                           |
| x86-64       | :heavy_check_mark:  |                                           |
| ARM          | :heavy_multiplication_x: |  Should work as before    |
| AARCH64      | :heavy_multiplication_x: |   Should work as before   |
| MIPS         | :heavy_multiplication_x: |   Should work as before   |
| POWERPC      | :heavy_multiplication_x: |    Should work as before   |
| SPARC        | :heavy_multiplication_x: …
=> Improve identifying Stack Canaries

gef.py
Added pushfd, popfd, pushfq, popfq instructions
keep x86 and x86_64 FLAGS Register when calls to mprotect
**This PR is not strictly necessary because "int 0x80" and "syscall" dont change x86/x86_64 flags and our mprotect-payload only uses mov instructions**. But in my opinion, our execution of mprotect should be stealthy, so it's best to always use push-flags as a good practice.
payload execution will be more safe (a little) when some gef-dev/user modify mprotect-payload with instructions that modify the flags 
| x86-32       | :white_check_mark:                      |                                           |
| …
=> keep x86 and x86_64 FLAGS Register when calls to mprotect. 

docs/commands/patch.md, docs/commands/print-format.md, gef.py, tests/commands/patch.py, tests/commands/print_format.py
With this PR print-format and patch byte commands can work together
Very handy to copy-paste-execute shellcodes/data from different memory regions
Alternative for: "set" / "dump" & "restore" ... GDB commands
**Example of use:**
```
gef➤  patch byte $rip 0x41 0x42 0x43
gef➤  hexdump byte $rip
0x00007ffff7fcd050 <_start+0000>    41 42 43 e8 18 0d 00 00 49 89 c4 8b 05 97 ec 02    ABC.....I.......
0x00007ffff7fcd060 <_dl_start_user+0008>    00 5a 48 8d 24 c4 29 c2 52 48 89 d6 49 89 e5 48    .ZH.$.).RH..I..H
0x00007ffff7fcd070 <_dl_start_user+0018>    83 e4 f0 48 8b 3d c6 ff 02 00 49 8d 4c d5 10 49    ...H.=....I.L..I
0x00007ffff7fcd080 <_dl_start_user+0028>    8d 55 08 31 ed e8 d6 ef 00 00 48 8d 15 5f f1 00    .U.1......H.._..
gef➤  hexdump byte $rsp+8
0x00007fffffffe068     b5 e3 ff ff ff 7f …
```
=> new feature: print-format and patch byte commands can work together

tests/commands/print_format.py
Minor fix to `tests/print_format.py`
| x86-32       | :white_check_mark:                      |  |
| x86-64       | :white_check_mark:                      |                                           |
| ARM          | :white_check_mark:                      |                                           |
| AARCH64      | ❌                       |                                           |
| MIPS         | :x:                      |                                           |
| POWERPC      | :x:                      |                                           |
| SPARC        | :x:                      | …
=> Minor update to unittest of `print-format` after #843

gef.py
Create a new root class for file formats (`FileFormat`) that subclasses will automatically use to register as a file format candidate. Each subclass must have a `is_valid(pathlib.Path) -> bool` function to be valid. When checking for a file format, the first valid class will be taken. 
Currently, only `Elf` stays builtin to GEF but see PR https://github.com/hugsy/gef-extras/pull/68 for PE and MachO support.
| x86-32       | :white_check_mark:                      |  |
| x86-64       | :white_check_mark:                       |                                        |
| ARM          | :x:                      | …
=> Allow new file format

gef.py, tests/commands/pattern.py
This PR fixes #857 
| x86-32       | :white_check_mark:                      | |
| x86-64       | :white_check_mark:                      |                                           |
| ARM          | :white_check_mark:                      |                                           |
| AARCH64      | :white_check_mark:                      |                                           |
| MIPS         | :x:                      |                                           |
| POWERPC      | :x:                      |                                           |
| SPARC        | :x:                      | …
=> [pattern-search] Make sure pattern is correctly built

docs/commands/search-pattern.md, gef.py, tests/commands/search_pattern.py
```
search-pattern --regex 0x401000 0x401500 ([\\x20-\\x7E]{2,})(?=\\x00)   
```
It matchs null-end-printable(from x20-x7e) C strings (min size >=2 bytes)
x86_64 binary POC:
[poc.zip](https://github.com/hugsy/gef/files/9031450/poc.zip)
=> --regex support for search-pattern command

gef.py
improve search-pattern code quality
=> search-pattern better code

gef.py
max size preview of bytes for print-format command can be changed via config
=> max size preview of bytes for print-format command can be changed via config

README.md, docs/install.md
Quick fix for #867 : updated the tinyurl links to perform the in-gdb installation
=> Fixed TinyUrl links to point to `main`, not `master`

gef.py
Removed `glibc-function-args`, moved to GEF-Extras
Also adds the possibity to specify a callback when calling  `register_external_content_pane`. This callback serves as a way to conditionally display the pane.
See:
* https://github.com/hugsy/gef-extras/pull/75
=> Remove `glibc-function-args` 

docs/install.md, scripts/gef-extras.sh
Before this PR, **gef-extras.sh** installation script uses **dev branch** by default.
main will be the default branch for gef-extras and gef installation. Also, it should be reflected in documentation.
Also I updated doc because standard users (non-devs) should use git clone with --branch main.
IMO this PR **must be merged in main** (2022.06 - Upset Constant) as hotfix because installation via **gef-extras.sh** ONLY installs **dev branch** and dont works correctly with **gef main**.
=> main will be the default branch for gef-extras and gef installation

gef.py
This changes the ptrsize on ARM to properly reflect that ptrsize will always be 4 even in thumb mode. This allows the stack and tele to both increment by 4 instead of 2, properly allowing gef to dereference pointers.
Relevant code:
```python
@property
def instruction_length(self) -> Optional[int]:
return None if self.is_thumb() else 4
@property
def ptrsize(self) -> int:
return 4
```
=> Fix ptrsize for ARM to not return 2 ever

gef.py
Signed-off-by: roderick <ch22166@163.com>
Sometimes, the old method `list(new_ptses - old_ptses)[0]` cannot get the right pty while meeting other tmux-pty operations at the same time. And it's better to kill the pane generated by tmux after quitting gdb.
=> get pty by tmux command and close pane when gdb exit

gef.py, tests/regressions/gdbserver_connection.py
This solves an issue with the `__del__` magic method being called unreliably, in particular it will often get called just when creating a new remote session using `gef-remote` which causes an exception in the `__del__` hook:
```
<method 'disconnect' of 'gdb.EventRegistry' objects> returned a result with an exception set
```
Because of this exception gdb has to be restarted before using the `gef-remote` command again.
=> Explicitly close the remote session

gef.py
because I got really sick of it
=> print warning messages when using `target remote` with gef

.gitignore, gef.py
Solve issue https://github.com/hugsy/gef/issues/877.
=> Fix Safe-Linking (GLIBC >= 2.32) and malloc_state struct

docs/faq.md, gef.py, tests/api/gef_session.py
When attaching to a process in a container, GDB prefixes file paths with `target:`, which means files can't be resolved. This also causes usage issues with output like
```
─────────────────────────────────────────────────────────────────────────────────── registers ────
[!] Command 'registers' failed to execute properly, reason: max() arg is an empty sequence
─────────────────────────────────────────────────────────────────────────────────────── stack ────
0x007ffd60a2b9b8│+0x0000: 0x007fdbeab206fa  →   pop rsi
0x007ffd60a2b9c0│+0x0008: 0x007fdbeab64b84  →  0x0000000000000000
0x007ffd60a2b9c8│+0x0010: 0x0000000000000000
0x007ffd60a2b9d0│+0x0018: 0x007ffd60a2ba28  →  0x00000000000003d6
0x007ffd60a2b9d8│+0x0020: 0x007fdbeab64b7c  →  0x0000000200000000
0x007ffd60a2b9e0│+0x0028: …
```
=> Fix filesystem paths for debugging process in containers

gef.py
If you `reset_architecture("something")` it'll set the arch, but then continue to try to figure out the architecture.
=> reset_architecture: Return after setting arch to a specified arch

gef.py
Respect the `GDBHISTFILE` env var
Fixes #909
=> Respect the `GDBHISTFILE` env var

docs/testing.md
Just a fix for the documentation for anybody not familiar with pytest (like me).
=> Fix test command in documentation

gef.py
Hey,
I've updated the shellcode format on shell-storm. Here is the fix on the gef plugin.
=> Fix shell-storm new API

gef.py
Closes #910 
Allows disabling Gef's internal buffer, which can improve usage of long-running commands (such as #906). 
=> Add option to disable output buffering

gef.py, tests/commands/canary.py
This PR adds arch-specific methods to find the *actual* canary location, as stored in `$fs_base+0x28` on x86_64.
This allows printing the in-use canary location, which can help with exploits that involve overwriting the canonical canary.
I wasn't able to find a way to read the `gs` segment on 32-bit, so currently this PR only adds functionality to x86_64.
=> Determine the actual canary location

gef.py, tests/api/misc.py
Fixes #905 
Detects when we're connected to a QEMU kernel instance, and uses `monitor info mem` to retrieve the real kernel memory mappings for searching within.
I will add tests shortly, just leaving this initial draft.
=> Fix searching when connected to `qemu-system` instance

.github/workflows/run-tests.yml, gef.py, tests/api/gef_disasemble.py, tests/binaries/mmap-known-address.c
This fixes #922 by safely failing when gef fails to disassemble previous instructions due to memory boundary.
=> Don't error out if disassembling previous instructions fails

docs/commands/dereference.md, gef.py, tests/commands/dereference.py
This commit extends the `dereference` command, allowing to examine memory backwards via a negative `--length` value, analogous to the behaviour of `x`.
=> Add backwards memory examination for the dereference command

.github/workflows/coverage.yml, .github/workflows/run-tests.yml
Move coverage to separate job on CI, to only send coverage results as comment to the PR (instead of failing it if lower).
This will give us a per-commit improvement for the PR. Based on that info, we can then decide to approve or reject if the drop is too high. This is less aggressive that failing the CI tests.
N/A (CI only)
=> [CI] Make coverage generate pull request comment instead of blocking validation

docs/index.md
I removed a sentence on the home page which states that GEF supports both Python 2 and Python 3 since Python 2 is no longer supported.
=> Remove outdated sentence in docs

gef.py, tests/commands/nop.py
Fix a bug in `nop` where the address range we calculate is wrong by one byte. This can lead to refusal to nop the last byte of a writable page if the next byte is read only.
```bash
gef➤  nop --nb 16 0x000055555555FFF0
[!] Cannot patch instruction at 0x55555555fff0: reaching unmapped area
gef➤  nop --nb 15 0x000055555555FFF0
[+] Patching 15 bytes from 0x55555555fff0
gef➤  x/16b 0x55555555fff0
0x55555555fff0: 0x90    0x90    0x90    0x90    0x90    0x90    0x90    0x90
0x55555555fff8: 0x90    0x90    0x90    0x90    0x90    0x90    0x90    0x0
```
=> nop: Fix off-by-one in unmap check

.gitignore
add site/ directory generated by mkdocs to .gitignore
=> add site/ directory generated by mkdocs to .gitignore

docs/commands/nop.md, gef.py, tests/commands/nop.py
```
The `nop` command allows you to easily patch instructions with nops.
```
nop [LOCATION] [--i ITEMS] [--f] [--n] [--b]
```
`LOCATION` address/symbol to patch (by default this command replaces whole instructions)
`--i ITEMS` number of items to insert (default 1)
`--f` Force patch even when the selected settings could overwrite partial instructions
`--n` Instead of replacing whole instructions, insert ITEMS nop instructions, no matter how many instructions it overwrites
`--b` Instead of replacing whole instructions, fill ITEMS bytes with nops
gef➤ 	nop
gef➤ 	nop $pc+3
gef➤ 	nop --i 2 $pc+3
gef➤ 	nop --b
gef➤ 	nop --b $pc+3
gef➤ 	nop --f --b --i 2 $pc+3
gef➤ 	nop --n --i 2 $pc+3
```
=> add new nop command features

gef.py
Clean up a simple function, because the only call to it did not respect the type hint.
Some opportunistic set stuff cleaned up as well.
=> Small cleanup - sets

LICENSE, gef.py
The behavior of the autosave file for breakpoints got broken in #839. This PR restores it.
Fixes #965 
It also updates all 2022 references in the code to 2023
=> Restore `autosave_breakpoints_file` behavior

gef.py, tests/commands/nop.py
Fixes ARM and ARM64 NOP instructions
Fixes an off-by-one in `gdb_get_nth_next_instruction_address()` for fixed-size instruction archs.
Result: `nop` works fine on ARM/AARCH64
=> Fix hardcoded NOP instructions for ARM/AARCH64

README.md
Just wrap according to _.editorconfig_
=> reformat README

README.md, docs/index.md, docs/install.md, mkdocs.yml
- Added more explicit references to gef-extras
- Added a note about required binaries (fixes #973)
Not applicable
=> Minor additions to the documentation

docs/faq.md
=> fix issue link

.github/CONTRIBUTING.md
under license mit -> under mit license
=> under license mit -> under mit license

.github/workflows/coverage.yml
add forbidden words checks to coverage action
=> add forbidden words checks to coverage action

.github/workflows/coverage.yml
Purely CI PR: use `pull_request_target` with custom permission to ensure external PRs can still trigger the coverage script.
=> [CI] Use `pull_request_target` for coverage trigger

.github/PULL_REQUEST_TEMPLATE.md, docs/debugging.md, scripts/vscode_debug.py
No code change, purely docs.
This PR adds the documentation to use VSCode as a source debugging platform for GEF.
It also fixes the PR template MD file, which had a non-terminated HTML comment tag.
=> Added docs to debug using VSCode

gef.py
Should fix #901's second issue, where we have trouble figuring out the memory map when the remote's path has a space in it.
It's due to how we generate a GDB command.
=> gef-remote: Fix issue with remote path having a space

gef.py
=> Tiny cleanup

gef.py, tests/config/__init__.py
This change makes it so that write hooks see the actual value provided to a setting when `gef config` is used, and gives it the chance to raise an exception if the value is invalid.
It also adds a validator 'no_spaces' and adds it to a few settings that use filepaths, since we know (from #999) that some GDB commands completely break when paths have spaces and/or when paths are quotes.
=> Let GefSetting write hooks see value

gef.py
As I looked into #901, I found that we often don't quote filepaths in `gdb.execute`. This began lazy grep that tries to ID where we do this, and fixes where we can. Noticed that we cannot use quotes in the filename when setting up logging, so it instead restricts the logging path to one without spaces.
This is mostly untested.
=> Fix gdb.execute not quoting paths

gef.py
gdb's `source` doesn't understand quotes. Annoying.
We should be OK not quoting it since the config has a hook to ensure the path doesn't have spaces.
Discovered by @southball
=> Do not quote paths when running 'source'

docs/commands/context.md, gef.py
This patch modifies the text shown above the source window as part of the `context_source()` function.
I'm working on a complex C++ project, with many directories and files.
Before this change I would get a split with...
`────────────────────────── source:/server/externa[...].cpp+130 ────`
which does not tell me anything about what file I am in, other than its extension.
After the change, I get something like this:
`─────────────── source:/server/externa[...]SendReceive.hpp+110 ────`
Depending on the length of the path the following may be shown:
* `if len(fn) <= 30`
* show the full path
* `elif len(basename(fn)) < 20`
* show `<first 15 chars>[...]<basename>`
* else
* show `<first 15 chars>[...]<last 10 chars>`
=> show basename in source: split line

scripts/gef-extras.sh, scripts/gef.sh
Make install scripts use the latest tag for scripted installation, not `main` by default.
Even though it should always be stable, `main` may be broken between releases, especially with its extras integration. It's safer to always point new users only to the latest known stable point.
=> [Installers] Use latest tag, not main

gef.py
Reorder how on reset_architecture fn is going to find arch. Now:
- Param forced
- Elf header
- gdb conf
It is based on chat on #947 with @Grazfather 
This change is needed because if first check for gdb conf if some has another language active would raise an exception making gef not work at all (some code match only english sentences).
This pattch would help non englihs users of gdb to not have many problems to use gef.
-  [ ] My change includes a change to the documentation, if required.
=> Reorder reset_arch: param forced, elf header, gdb conf

.github/workflows/validate.yml
Python 3.12 doesn't work because of some lib being deprecated.
=> Run validate CI step with Python 3.11

docs/commands/gef-remote.md, gef.py, tests/commands/gef_remote.py
As mentioned in Gallopsled/pwntools#2264, gef does not work properly with many tools that rely on the `target remote` command.
In this PR, I propose a fix that uses a remote posthook in order to instantiate and setup the GefRemoteSessionManager after the connection being established.
Note that this isn't a perfect solution since we do not have all the information needed for a proper instantiation of the GefRemoteSessionManager, but it seems to be a good workaround in order to make tools like `pwntools` work correctly with gef.
=> [target-remote] Basic support for the `target remote` command

.github/workflows/coverage.yml
Coverage workflow should only be triggered by `pull_request`. 
In addition, even if it worked, that would post twice the exact same message (once from `pull_request`, another from `pull_request_target`).
Error example to avoid:
=> Coverage workflow should only be triggered by `pull_request`

docs/commands/heap.md, gef.py, tests/commands/heap.py
This change adds 2 things:
1. When listing the arenas, it shows the memory usage and peak memory usage
2. It adds `--summary` option to `heap chunks` command. Instead of dumping all chunks, it dumps the summary of all the chunks, grouped by size and flags.
This helps us to get a high level of the distribution of the objects on the heap, which helps debugging memory issues.
For example, this is one of our recent memory analysis:
1. With memory usage showing in the arena list, we immediately know the main arena is causing the problem here.
```
gef➤  heap arenas
Arena(base=0x7f5b3ebd1b80, top=0x55f4c0a36d60, last_remainder=0x55f47c4147a0, next=0x7f5b08000020, mem=1274572800, mempeak=2359623680)
Arena(base=0x7f5b08000020, top=0x7f5b08051260, last_remainder=0x7f5b08017030, next=0x7f5b10000020, …
```
=> Dump memory usage when listing arenas, and add summary option in heap chunks command.

gef.py, tests/api/misc.py, tests/commands/gef_remote.py
This change allows architectures to provide their own memory map by defining `maps` in the architecture. If set, then `GefMemoryManager` will defer to it when building maps.
This can be used for e.g. architectures that are built for use with gdbserver.
It also adds `parse_info_mem` (Renaming the old one to `parse_monitor_info_mem`) which parses the maps from this command. The Black Magic Probe provides memory maps of its targets via this command.
=> Memory map provider

gef.py
The change is to fix the timing of clearing the screen for showing debugging context.
According to doc, when enabled, before showing the debugging context, screen will be cleaned.
```
Clear the screen before showing the context sections when breaking:
gef➤ gef config context.clear_screen 1
```
This is helpful to keep the debug experience focused, but the timing seems to be broken with the current code.
Currently, clearing screen will happen after all contexts are shown. Hence, whenever a breakpoint is hit, all contexts will be off the screen leaving only the input prompt as screenshot shows below.
The screenshot here shows the screen output after a breakpoint it hit:
This change moves the clear screen to the time before showing the context, hence fixing the problem.
Here is the screenshot …
=> Fix clear-screen timing when showing context

docs/commands/heap.md, gef.py, tests/commands/heap.py
This change adds `--min-size` and `--max-size` filter to heap chunks command.
With heap summary, we can quickly use `--min-size` and `--max-size` filter to find some sample chunks for further analysis. 
Here are the screenshots as demo:
=> Add min-size and max-size filter to heap chunks command

docs/commands/heap.md, gef.py, tests/config/__init__.py
This change add a config for force the libc version to a specific version.
This is helpful when debugging certain core dumps that doesn't have good memory map information, and could not find libc properly.
This shows up in our recent debugging, where we know the program is using libc 2.31, but it could not be detected properly due to memory map information missing.
The screenshot below shows the libc version missing problem, which results failures when dumping the heap:
- libc version missing:
- having trouble dump heap arenas (see top == 0, while arena pointer is right):
This change allows us to force the libc version into a specific version, which solves this problem.
Here is the screenshots that demos the fix:
-  [x] My change …
=> Add config to override libc version.

docs/commands/heap.md, gef.py, tests/commands/heap.py
This change adds `--resolve` option to resolve the type and categorize the chunks, using vtable in the chunk. 
Since multiple types of objects could share the same size, also it is impossible for anyone to remember the size of all the objects in the system, categorize and output the chunks by object type will become very handy when debugging issues like memory leaks.
Here is a screenshot to show how the change works:
In this test process, we can see we created 23423 Task objects, which pops up and might indicate a leak.
=> Add option to resolve type when dumping heap summary.

tests/api/gef_disasemble.py, tests/api/gef_heap.py, tests/api/gef_session.py, tests/api/misc.py, tests/commands/canary.py, tests/commands/checksec.py, tests/commands/format_string_helper.py, tests/commands/gef_remote.py, tests/commands/got.py, tests/commands/heap.py, tests/commands/heap_analysis.py, tests/commands/memory.py, tests/commands/nop.py, tests/commands/patch.py, tests/commands/pattern.py, tests/commands/pcustom.py, tests/commands/pie.py, tests/commands/process_search.py, tests/commands/scan.py, tests/commands/skipi.py, tests/commands/xinfo.py, tests/functions/elf_sections.py, tests/regressions/registers_register_order.py, tests/utils.py
This change renames the tests.utils._target function to tests.utils.debug_target
Currently, many tests are required to access the `_target` function in test_utils for building proper test cases. Hence, it is better to remove the _ prefix for this function, give it a more proper name, really make it public.
This requirement comes from the discussion here: https://github.com/hugsy/gef/pull/1028#discussion_r1433369804.
-  [-] My change includes a change to the documentation, if required.
-  [-] If my change adds new code, [adequate tests](docs/testing.md) have been added.
=> Rename _target to debug_target for building test cases.

scripts/gef.sh
This is mainly because Arch Linux no longer ships `which` in `base`:
```console
$ bash -c "$(curl -fsSL https://gef.blah.cat/sh)"
bash: line 9: which: command not found
bash: line 11: which: command not found
Please install cURL or wget and run again
```
Note: no docs/tests added, but I checked the boxes because I don't think they are needed.
I tested the modified`./gef.sh` locally.
=> gef.sh: Fix `which: command not found`

docs/api.md
Since #866 it's possible to hide custom context panes using a callback function. I only found out about this useful feature by reading the code. This PR documents it.
=> [docs] document conditional context panes

gef.py
The `return (int) X` command in gdb only sets the 4 lowest bytes of the return register. For example if `rax` was `-1`, a `return int 0` would leave us with `0xffffffff000000` instead of `0x0`.
This patch makes `StubBreakpoint` check for the register size and executes `return (int)` or `return (long)` accordingly.
=> support 64 bit retval for stub

docs/commands/heap.md, gef.py, tests/commands/heap.py
This change add `--count` option in heap chunks command to limit the number of chunks to process / output.
Currently, since we don't have the count limit, even with the size filter, we might get too many chunks in the output, especially when debugging large dumps.
With this change, we can use `--count` option to give us only a few samples to check what might be happening, e.g. large buffers with certain special size.
Here is the screenshot that demos the usage (mixed with `--min-size`)L
=> Add count option in heap chunks command to limit the number of chunks to process / output.

gef.py, tests/commands/xinfo.py
As stated in the comments `info symbol` returns "`<symbol_name> + <offset>`" with spaces around the `+`. The current split leaves a space in front of the offset which makes .isdigit() return False.
@r12f, do you think we still need the `.strip()` for `sym[0]` ?
=> correct parsing in gdb_get_location_from_symbol

.github/workflows/coverage.yml, .github/workflows/validate.yml
Restore the coverage comment functionality for PRs to a workable state
The reason it's broken is because of different security permissions between actions triggered by `pull_request` and `pull_request_target`.
This will need to be improved carefully by testing non-project commitors successfully trigger the action.
=> Restore CI coverage

.github/workflows/coverage.yml, .github/workflows/validate.yml, gef.py, tests/api/gef_memory.py, tests/api/misc.py, tests/base.py, tests/utils.py
Use `info proc mapping` as a first memory layout enumeration technique.
Removed `maintenance info sections` which is not about memory layout
=> Use `info proc mapping`

gef.py
Fixes #1049
Removes from `typing` imports the `Literal` member which appears on Python 3.8.
Since it's never used anyway, it shouldn't be here in a first place. Wonder how linting missed this 🤔 
Also it seems adding target hooks overlooked the compat also. Since we might upgrade the base versions soon, the feature is just disabled for now
=> Restore compatiblity with Python 3.6

gef.py, tests/commands/gef.py, tests/commands/pcustom.py, tests/config/__init__.py
This PR  is purely esthetic but fixes a few extra inconsistencies thanks to type hints, using `pylint` and `pylance`.
Both pass now reporting no error, warning or info!
Among other fixes:
* removed unused vars
* `f-string`-ify more
* enforce (using `assert`) expected type to variable when appropriate
* fixed some bad type names in `gdb.events.*`
* the config manager allows to receive non basic types
* applied all the type issues spotted by pylance using the gdb.pyi stub
* a lot of `staticmethod` have been made non static because we can use `gef.gdb.commands["XXX"]` instead
With this PR :
* `pylint` on gef and tests/*.py shows a 10/10 score
* `pylance` shows no error 
-  [x] My change includes a change to the documentation, if …
=> Killing the last inconsistencies through type hints

gef.py
get python version using the stem function from pathlib instead of list slicing
with list slicing assertion fails while using pyenv bacuse the path is wrong
=> fix python version parsing

.github/workflows/run-tests.yml
We used `-k "not benchmark"` which would filter out ANY test that contained the word 'benchmark'.
This change fixes that by using the `-m` argument to only filter on marks.
=> workflows: tests: Fix arg to check marks

gef.py
Removed one debug print, and replaced `typing.OrderedDict` with `typing.Dict` (brings little and breaks compat)
=> Restore support for Python3.6 on LTS 18.04

gef.py
`gef.session` points to a session manager and keeps state, but was often referencing `gef.session` instead of `self`. Also, some checks for remote sessions were unnecessary: Since the session has a remote attribute, callers on the session can count on the session manager to provide the correct data/function
=> Cleanup session managers to encapsulate & defer better

gef.py
Add a post hook to `source` to automatically reload `gef` commands and move `@register`-ed new commands to being active.
TODO: figure out when posthook appeared for compat
-  [ ] My code follows the code style of this project.
-  [ ] My change includes a change to the documentation, if required.
-  [ ] I have read and agree to the **CONTRIBUTING** document.
=> Add a `source` post hook

gef.py, tests/commands/entry_break.py, tests/commands/highlight.py
Quick fix for a nasty bug I discovered last night:
For (at least) ARM and ARM64`$arch.ptrsize` is calculated dynamically from CSPR flags, and invokes `parse_address`. However, `parse_address` requires `ptrsize` to be set to determine the alignment. 
So we end up in an infinite loop. Which breaks almost everything.
Example on ARM64
```console
↳ File "/home/hugsy/code/gef/gef.py", line 3844, in parse_address()
→     return to_unsigned_long(gdb.parse_and_eval(address))
↳ File "/home/hugsy/code/gef/gef.py", line 2351, in __get_register_for_selected_frame()
→     return parse_address(regname)
↳ File "/home/hugsy/code/gef/gef.py", line 2345, in __get_register()
→     return self.__get_register_for_selected_frame(regname, int(key))
↳ File "/home/hugsy/code/gef/gef.py", line 2363, in register()
→ …
```
=> Fix recursive loop on architectures where `flags` register is a dynamic value

gef.py
If gdb is recent enough this patch uses `breakpoint.locations` to extract directly the address at which the breakpoints are set instead of parsing the command used by the user.
As discussed in #1039 the previous implementation only worked if the user sets the breakpoint with a format "b *{hex(address)}"
=> Support breakpoint.locations

gef.py
We hardcode string deref length to 50, but we don't use this constant in `dereference_from`.
See #1074
=> dereference_from: Use GEF_MAX_STRING_LENGTH

gef.py
`flag_register_to_human` is not implemented in all architectures, such as RISCV.
This issue will crash `context` command.
This issue is confirmed in gef dfd3868e353a00f4aa8215f2f00263ffb961d0db.
Note: The backend is an openocd instance and VisionFive2 board over Jlink debugger. 
However, I am convinced this issue is unrelated to the specific backend configuration.
```
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting …
```
=> `flag_register_to_human` is not implemented on RISC-V architecture

docs/deprecated.md, gef.py
Removes pyenv related functionality from gef.py.
See discussion at https://github.com/hugsy/gef/issues/1078
=> Remove pyenv related code (closes #1078)

docs/commands/vmmap.md, gef.py, tests/commands/vmmap.py
Attempts to parse and eval an argument passed to `vmmap`.
This makes `vmmap $rip`, for example, work.
This is useful as it is easier to look up the memory section a pointer contained in a register/variable points to. It's also more consistent with commands like `dereference`
=> Evaluate arguments passed to `vmmap`

gef.py
This PR fixes some issues in the setting loading process resulting in the default value always being taken for gef-extras scripts (as underlined by hugsy/gef-extras#107
`GefSetting` now offers the possibility to trigger a callback, `on_changed` which behaves just like `on_write` but only if the value was changed.
=> Add `on_changed` setting hook

gef.py, tests/api/misc.py, tests/binaries/Makefile, tests/binaries/collision.c, tests/regressions/filename_collision_lookup.py
- Find the `main_arena` even if there is "libc" in the path of files that aren't libc.
- Warn the user when there are multiple matches when using `$_base("xxx")`
- Search for "xxx" in the filename instead of the entire path when possible when using `$_base("xxx")`
```
(remote) gef➤  vmmap
[ Legend:  Code | Heap | Stack ]
Start              End                Offset             Perm Path
0x000061077d582000 0x000061077d583000 0x0000000000001000 r-- /home/user/ctf-fcsc/file-checker-src/public/file-checker_remotelibc
0x000061077d583000 0x000061077d584000 0x0000000000001000 r-x /home/user/ctf-fcsc/file-checker-src/public/file-checker_remotelibc
0x000061077d584000 0x000061077d585000 0x0000000000001000 r-- /home/user/ctf-fcsc/file-checker-src/public/file-checker_remotelibc
0x000061077d585000 …
```
=> Fix problems due to multiple matches in filename filters

docs/api.md, gef.py, scripts/gef-extras.sh
This fixes all the issues with the context panes and it now works as it did before the plugins were created. 
In the GEF part, it was just a minor refactor and a new external API. 
In the gef-extras part, it was only necessary to call this new function!
I think the proposed solution is simple and it works.
gef-extras code:
- https://github.com/hugsy/gef-extras/pull/111
=> add layout mapping API for external plugins

docs/install.md, gef.py
This change moves the setup of the line describing a GOT entry into a method in order to support the "got-audit" command, which is a subclass of the GotCommand.  It also uses a full-width output from readelf, and gets the path for `nm`, both of which also support the got-audit command as a subclass.
=> Supporting changes for the "got-audit" command.

gef.py, tests/api/gef_memory.py
Fix the Offset column in the `vmmap` command by getting the offset from the correct column in `parse_gdb_info_proc_maps`.
Before:
```
gef➤  vmmap
[ Legend:  Code | Heap | Stack ]
Start              End                Offset             Perm Path
0x0000555555554000 0x0000555555558000 0x0000000000004000 r-- /usr/bin/ls
0x0000555555558000 0x000055555556e000 0x0000000000016000 r-x /usr/bin/ls
0x000055555556e000 0x0000555555577000 0x0000000000009000 r-- /usr/bin/ls
0x0000555555577000 0x0000555555579000 0x0000000000002000 r-- /usr/bin/ls
0x0000555555579000 0x000055555557a000 0x0000000000001000 rw- /usr/bin/ls
0x000055555557a000 0x000055555557b000 0x0000000000001000 rw- [heap]
```
After:
```
gef➤  vmmap
[ Legend:  Code | Heap | Stack ]
Start              End                Offset …
```
=> Correctly parse offset from `info proc mappings` output (#1096)

gef.py
'set logging on/off' is deprecated and replaced with 'set logging enabled on/off'.
=> update: gdb logging enable/disable command

docs/api/gef.md, gef.py
`confortable` -> `comfortable`
Because #1081 is idle for too long
=> [Docs] Fix typo

docs/commands/got.md, gef.py, tests/commands/got.py
This change adds a "got-all" command which expands on the existing "got" command by providing data about relocations in mapped shared object files in addition to the relocations specific to the main executable.
Particularly for auditing purposes, users may be interested in the state of all relocations, not only those for the primary executable file.
=> Add an "--all" option to the got command

docs/commands/arch.md, gef.py, tests/commands/arch.py
Available subcommands:
- get  -> prints the current arch and the reason
- set  -> manually set the current arch (or auto-detect if no arg is provided)
- list -> list available architectures
Implements this: https://github.com/hugsy/gef/issues/1002
=> [cmd] Add a `arch` command for managing `gef.arch`

gef.py
On a 2.30 libc, the string `glibc 2.30` was on a `r-x` page instead of a `r--` page.
Checking all readable pages would not affect performances too much since it is unlikely to have lots of libc maps, and this function is not called often.
=> [libc] Fix `find_libc_version` for checking each readable maps

tests/api/gef_memory.py, tests/api/gef_session.py, tests/commands/canary.py, tests/commands/gef_remote.py, tests/commands/scan.py, tests/commands/vmmap.py
Restores tests on non-x86 (tested arm, arm64 and mips64)
Mostly very minor fixes, only unit tests related.
Qemu tests are temporarily disabled when remoting because they all assume host & target are Intel (not blocking, but must be reworked later).
=> [Release 2024.06] Fixes

gef.py
Add support for the `append` action for ArgumentParser in the `parse_arguments` decorator on optional arguments.
This makes us able to support this:
```
command --arg 1 --arg 2 --arg 3
```
And get `[1, 2, 3]` as the `arg` value.
This CL is required to make changes to https://github.com/hugsy/gef/pull/1120 before merging.
=> [internal] Add a way to append values to optional arguments in `parse_arguments` decorator

gef.py
In #1093, a call to `add_context_layout_mapping` was added without the `self` scoping, causing a crash when external plugins add a context pane to GEF. I triggered this in the latest version of d2d:
```
Python Exception <class 'NameError'>: name 'add_context_layout_mapping' is not defined
Error occurred in Python: name 'add_context_layout_mapping' is not defined
```
If possible, I'd recommend adding a linter check as a requirement to the CI, so simple bugs like this can be caught :).
=> Fix an incorrect scoped function call (introduced in #1093)

gef.py, tests/api/gef_memory.py
This change passes both the "display" path and the local "real" path for each section or file to the print_got_for function in GotCommand.  Without this change, the `got` command does not work properly in a remote debugging session.
=> Fix remote use of gef.memory.maps

scripts/gef.sh
To make python  using UTF-8 when outputting to the pipe
Some users in Asian regions using non-ASCII languages may encounter issues when installing GEF with mys2 on Windows. The error message might be: "UnicodeEncodeError: 'gbk' codec can't encode character '\u21b3' in position 5137: illegal multibyte sequence." The reason is that Python is not using UTF-8 when outputting to the pipe, so the -x parameter needs to be added.
Make installation easier
=> Fix python unicode encoding problem when install gef in non-ascii  locale

gef.py
There is a bug in how stack/heap addresses colors are shown in gdb using the `vmmap` command. This patch fixes it:
=> fixed color swap between heap/stack

gef.py, tests/api/gef_memory.py
fix for https://github.com/hugsy/gef/issues/1055
=> [memory] Fix read_cstring trying to read too far

docs/commands/vmmap.md, gef.py, tests/commands/vmmap.py
Parse args:
- `-a` / `--addr`:
- filter by address -> parses the next arg as an int or asks gdb the value
- `-n` / `--name`:
- filter based on section name
- If nothing is specified, print a warning and guess the type (previous behavior)
=> [cmd] Add support for flags specifying filters type in vmmap, and allow multiple filters

gef.py
The implementation of the `which` function only checks for the executable flag on paths, which means it can return a directory (at least on POSIX), causing weird permission errors down the line. It should instead defer to `shutil.which`; that function contains a platform-agnostic implementation that should hopefully match the behavior of the GNU `which` utility.
=> Use shutil when looking for executables on the host system

gef.py
Add a new GEF config item
```
───────────────────────────────────── GEF configuration setting: gef.clear_screen_command ─────────────────────────────────────
gef.clear_screen_command (str) = "clear -x"
Description:
Command to use to clear the screen.
```
Fixes #1147 
=> Simplified clear screen command

gef.py, tests/commands/context.py
Make sure panes added in `context.layout` have a unique name
Fixes #1145
=> Prevent duplicate panes in `context.layout`

gef.py
When analyzing a coredump, always prefer `maintenance info sections` over `info proc sections`
Fixes #1154
=> Use `maint info sec` for coredumps

gef.py
The caller shouldn't need to know to make it lower case.
=> reset_architecture: Force arch to lower case

docs/api/gef.md, docs/commands/config.md, docs/commands/dereference.md, docs/commands/gef-remote.md, docs/commands/gef.md, docs/commands/heap-analysis-helper.md, docs/commands/memory.md, gef.py, scripts/new-release.py, tests/utils.py
-  [ ] My code follows the code style of this project.
-  [ ] My change includes a change to the documentation, if required.
=> fix typos treewide

gef.py
This fixes `bge` and `bgeu` branch prediction for RISC-V due to a typo in the original code.
=> Fix bge/bgeu for RISC-V

gef.py
Fix the permission checks in `Section` by using [enum.Flag.\_\_bool\_\_](https://docs.python.org/3/library/enum.html#enum.Flag). For `enum.Flag`, != 0 always returns `True`, as the test below.
```python
import enum
class Permission(enum.Flag):
NONE = 0
EXECUTE = 1
WRITE = 2
READ = 4
ALL = 7
p = Permission(0)
print(p, p != 0)  # Permission.NONE True
```
The fixed functions are rarely called. I found this when porting `Section` to [llef](https://github.com/foundryzero/llef). I also have checked all  `!= 0` and found no similar error.
-  [x] I have read and agree to the …
=> fix enum.Flag empty check

tests/binaries/heap-multiple-heaps.c, tests/binaries/heap-non-main.c
This patch modifies the `thread` function in two test files, so that it matches the expected prototype for an argument to pthread_create.  This fixes a build failure with gcc 15:
```
heap-non-main.c: In function ‘main’:
heap-non-main.c:27:40: error: passing argument 3 of ‘pthread_create’ from incompatible pointer type [-Wincompatible-pointer-types]
27 |         pthread_create(&thread1, NULL, thread, NULL);
|                                        ^~~~~~
|                                        |
|                                        void * (*)(void)
In file included from heap-non-main.c:8:
/usr/include/pthread.h:204:36: note: expected ‘void * (*)(void *)’ but argument is of type ‘void * (*)(void)’
204 |                            void *(*__start_routine) (void *),
| …
```
=> Use the correct type for function passed to pthread_create.

gef.py
This PR adds fallback path `/usr/lib/debug` to `debug-file-directory` config.
Closes #1169.
Some gdbs installed outside `/usr` (like nix or in user homedir) will not search
for dbgsyms in `/usr/lib/debug`. However `/us/lib/debug` is where most distros
package debuginfo symbols to.
```console
> /run/workspace/bin/gdb -q -x .gef.py -ex 'show debug-file-directory' -ex 'quit'
The directory where separate debug symbols are searched for is "/nix/store/k51rfv38p65jbhw906vpl85yg1vd7xqn-gdb-15.2/lib/debug".
```
```console
> /run/workspace/bin/gdb -q -x .gef.py -ex 'show debug-file-directory' -ex 'quit'
The directory where separate debug symbols are searched for is "/nix/store/k51rfv38p65jbhw906vpl85yg1vd7xqn-gdb-15.2/lib/debug:/usr/lib/debug".
```
-  [x] My code follows the code style of this …
=> Setup fallback 'debug-file-directory'

gef.py
Add a path argument to GotCommand build_line to support updates in GotAudit.
Related changes in hugsy/gef-extras/pull/122
In order to reduce false positives in GotAudit, the build_line function requires the path to the file whose symbols are being described.
=> Add a path argument to GotCommand build_line to support hugsy/gef-extras/pull/122

gef.py
Test case: https://github.com/shellphish/how2heap/blob/master/glibc_2.39/house_of_tangerine.c
Top chunk cannot be printed after it's size changed, pero top chunk always access by `arena.top`, it should always been printed ever with a malform size.
=> Always print top chunk when run `heap chunks -a`

gef.py
This PR fixes  a missing type check introduced by #1173 when getting result from `gdb.parameter` while setting ` debug-file-directory` 
=> Verify `gdb.parameter("debug-file"directory")` returns a string

scripts/gef-extras.sh
Fix location of syscall-tables for gef-extras installation script.
=> Fix location of syscall-tables for gef-extras installation script
