- gef.py
display on fastbin/bins has something wrong ?
my environment is GLIBC 2.21
have to rewrite some dirty code
> fix fastbin bug

- gef.py
Hi,
I added a command to use ropper in gef. Currently it uses the default commandline interface arguments. 
Best
Sascha
> ropper command added

- docs/index.md
I thought I add ropper to the dependencies in README :)
> added ropper to dependencies

- docs/features.md
- gef.py
> pcustom: Don't barf if struct dir doesn't exist

- gef.py
Instead of returning `None` when `lookup_address` cannot find an address
in the process address space, return an 'invalid' `Address` object. This
forces the callers check for the `valid` attribute instead of just
`None`, but also allows them to check the original address (`value`).
This fixes a bug in `pcustom` where if a struct's field looked like a
pointer but wasn't it showed up as zero.
> lookup_address: Always return an Address

- gef.py
Fixes #74 
Haven't tested on other systems, but I don't expect it to cause issues.
> context_trace: Restore current frame

- gef.py
NOT READY FOR MERGE. Only making PR so it's easier to review.
> Arch classes

- gef.py
I spent way too long in `git add -p` adding just the nice ones... and somehow, after 30 minutes git ignored all my adds.
I then ran a bunch of regex to put spaces around +, -, =, +=, -=, ==, and removed superfluous spaces inside parens.
> Less aggressively reformat

- gef.py
In python empty strings and empty lists are considered False.
(bool([]) == False) and (bool("") == False).
This means that anything that does
if len(l) > 0:
Can be replaced with
if l:
I will work on other changes if you like these.
> Make code more consistent/pythonic

- gef.py
I am working on this branch so that each change can stand alone: Feel free to cherry pick as you please.
1. `ProcessListingCommand`: Yield processes instead of building the list. The list _is_ built at the end (in the memoized function) so it's not really a big speed improvement, and you might think it hurts readability. Also improves (imo) method naming.
2. `get_process_maps`: Use `for line in file` idiom plus yield results
3. Move `pprint_dereferenced` into a class member: This prevents us from having to compile the function every time `DereferenceCommand` is invoked.
4. Tiny cleanup: `format (...` => `format(`.
> Miscellaneous pythonic improvements

- docs/commands/nop.md
- docs/commands/stub.md
- gef.py
* Fixes bug in issue in #117
* Fixes another issue where nop just basically didn't work
* Splits `nop -p` into its own `stub` command.
> Fix nop -p corrupting stack, fix nop, turn nop -p into stub command

- docs/commands.md
- docs/commands/patch.md
- docs/index.md
- gef.py
This adds a simple `patch` command that can write a set of values at the specified address.
It also adds the windbg-style aliases.
> Add Patch command

- gef.py
I didn't correctly switch the strings in `GlibcHeapChunkCommand` to
properly append to the array, so the output was unreadable. The colour
setting was also broken. Both these issues have been fixed.
As an added bonus I catch the memory error if the chunk address is
invalid and spit out a nicer error.
> Fix heap formatting and hide memory exception

- gef.py
1. Detect loops that are longer than just self references.
$rax   : 0x7ffff7dd1000  →  0x7ffff7dd1008  →  0x7ffff7dd1000  →  [loop detected]
2. Check for addresses being in a valid section before derefencing
3. Use `string.printable` instead of a manual charset
4. Improve loop logic.
> DereferenceCommand: Improve loop, fix bad addr

- gef.py
> basic filter in vmmap (ex.: vmmap libc)

- gef.py
- ida_gef.py
for this pull request
1) bug fux: the breakpoint address parsing has something wrong in the original version
2) it can sync all breakpoints from gdb to IDA or IDA to gdb
3) the cursor in IDA is sync-ed automatically, beware the crash :(
4) pc sync with offset rather than absolute address, so that i can work on ASLR/PIE
and i haven't test and updated on BN
(@_wmliang_)
> update IDA interact and some bug fix

- gef.py
gef_instruction_n returns the incorrect instruction for `n != 0`:
This is fixed with the first commit:
This also fixes `gef_next_instruction` which gave the current instruction back instead of the next one.
But this breaks the code context!
Looking into this it seems `gdb_disassemble` uses a different definition of `end_pc` as GDB.
I changed the documentation so it is in line with the GDB documentation.
`gdb_get_nth_previous_instruction_address` assumed the other behaviour which is why it broke when `gef_current_instruction` got fixed. This gets fixed in the other commits.
gef_instruction_n returned the incorrect instruction for `n != 0`.
x86-64 and ARM
> fix gef_instruction_n off by one bug

- gef.py
Fixes #169
Also fixes a bug I found in `capstone-disassemble`'s argument parsing.
> Nb lines code prev

- gef.py
Ran pyflakes and fixed the issues (manually).
Please look over and let me do the merge.
> Clean up gef.py thanks to pyflakes

- gef.py
https://github.com/hugsy/gef/issues/XX
| x86-32       | :heavy_check_mark:       | rock'n roll            |
| ARM          | :heavy_check_mark:       |                        |
| MIPS         | :heavy_check_mark:       |                        |
| POWERPC      | :heavy_check_mark:       |                        |
| SPARC        | :heavy_multiplication_x: | Who uses SPARC anyway? |
> Simplify the formatting of sys_version_info

- .github/ISSUE_TEMPLATE.md
> Reword issue template

- gef.py
Add basic RISCV support such that using `gef` with [`riscv-binutils-gdb`] and the example
shown for using [`riscv-isa-sim`] [Debugging with GDB] should work.
- As of GDB 8.1.1 RISCV is not supported. As a result, I have not updated the docs etc
to add RISCV to the officially supported architectures
- This commit is essentially just what I could hack up last night and is far from a complete implementation
| x86-32       | :heavy_multiplication_x: | Not changed            |
| x86-64       | :heavy_multiplication_x: | Not changed            |
| ARM          | :heavy_multiplication_x: | Not changed            | …
> RISC-V: Add basic support for RISC-V

- gef.py
Fixes for comment in #310 
| x86-32       | :heavy_multiplication_x: |   |
Basic testing with RISC-V
> RISCV: Tidy fixes for RISCV class

- docs/commands.md
- docs/commands/scan.md
- gef.py
- mkdocs.yml
- tests/runtests.py
Fixes https://github.com/hugsy/gef/issues/326
| x86-32       | :heavy_check_mark: |                        |
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Search for cross references between sections

- .circleci/config.yml
- gef.py
> run pylint -E for python2 and 3 on gef.py

- gef.py
Note that I also changed a few other things
> New theme. Shh it's a surprise!

- gef.py
Should fix #353, but should be tested.
> remove _xlog and just use gef_print

- gef.py
For example in @Grazfather's tcache pr https://github.com/hugsy/gef/pull/363/files#diff-c1353c3dea65fb78135f4781a0dddab0R672
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hugsy/gef/366)
> A bit of refactoring so other gef functions can get the heap base

- gef.py
| x86-32       | :heavy_multiplication_x: |    |
> Add pyenv support

- Dockerfile
- requirements.txt
I created a requirements.txt file with the proper versions for the python project dependencies and updated the Dockerfile to install from there.
>  Issue #377 Created requirements.txt with hardcoded versions for project

- tests/runtests.py
> Add test for 'got' command

- .circleci/config.yml
> ci: Point to hugsy's dockerhub image

- gef.py
Make it easier to see what's going on in the template, since we can now use named format tags.
> emu: Use .format instead of % to format

- gef.py
> Align source extra info with code

- gef.py
> hexdump: Show chars even if not in 'byte' mode.

- gef.py
This PR fixes #433 by applying the changes from bminor/binutils-gdb@7022349d5c86bae74b49225515f42d2e221bd368 in GDB and explicitly stating a return type to `call`s.
> Issue #433: setting all calls to GDB `call`  with a return type

- gef.py
> get_ith_parameter: Add kwarg for in_func

- Makefile
- tests/runtests.py
This doesn't fix everything :( but it fixes the `test_cmd_patch_*` test cases, and makes things nicer.
> [Mostly] Fix ci

- gef.py
Fixes portability for macOS/FreeBSD/NixOS …
> Portability Fixes

- docs/commands/context.md
- gef.py
- scripts/gef-extras.sh
adds a def type after register/position and value, see #576
| x86-32       | :heavy_check_mark: | |
| …
> glibc function call argument definition

- gef.py
Fixes #599
1. Are we OK with this theme name?
2. Should it be generalized? e.g. what about old SOURCE lines?
3. Should we add a theme for old source lines
CC @mvastola
> Add theme colour for disassembly lines before PC

- gef.py
I noticed that gef doesn't display tcache in some cases and tracked it
down to gef confusing libcrypto (which starts with "libc") with an
unknown libc. Fix by skipping unknown libcs.
| …
> Fix libc version detection if libcrypto is loaded

- gef.py
I prefer this for the `theme.old_context` config and thought it might be useful
> feat: add color "light_gray"

- gef.py
On variable-length instruction ISAs we currently guess where the
instructions start by going back as far as possible and then checking
over and over again until we find some offset where we disassemble the
correct number of instructions. For the default settings on x86_64 this
has us go back 45 instructions and it often takes a good handful of
tries to find a valid offset.
This change adds an optimization:
Instead of capping the disassembly to n+1 instructions, disassemble up
to the start address, but use as many instructions as that would take.
If we happen to disassemble more than we need, that's fine, just grab
the last n+1, and validate that they are OK.
Further: We don't need to check each instruction for validity until we
make sure that the address of the last instruction matches. …
> get_nth_prev..._inst...: Look ahead and carve

- gef.py
> Pull dereference_command out of class to fix cache clearing

- scripts/ida_gef.py
> ida_gef: Add api map for DelBpt

- docs/commands.md
- docs/commands/gef.md
- gef.py
This PR adds docs for the `gef` command and its subcommands (as in issue #643).
N/A (docs)
Fixes #643
> Docs For GEF Command

- gef.py
- Added highlight of selected frame in backtrace
- Fixed frame level in contex_trace. For example, if full backtrace is
and selected frame level is 5, wrong levels in backtrace were shown
Now it is correct
Number of frames before selected frame is configured with `context.nb_lines_backtrace_before`. …
> Fix frame level in context_trace and highlight selected frame

- gef.py
Added `cc` and `cs` condition codes
| RISC-V       | …
> Add missing aarch64 condition codes

- gef.py
> nop: Fix default arg and docs

- gef.py
the world now contains 1 typo less 
extensively
> fix typo in search-pattern help

- .ci/mlc_config.json
- .github/workflows/docs-link-check.yml
- .gitignore
- docs/commands.md
- docs/commands/ida-interact.md
- docs/faq.md
The title says it all.
Fixes #729
| RISC-V …
> [CI] Use Actions to check URL links in the documentation

- gef.py
#779 brought in a bug in the classes handling the `gef save` and `gef restore` commands that prevented non default values to be stored & loaded.
This PR fixes that bug.
| ARM          | :heavy_check_mark: |                                           | …
> Fixed bugs in `GefSetting` that prevented saved values to be loaded

- LICENSE
- gef.py
> Prevent major catastrophe

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/discord-notify.yml
- .github/workflows/generate-docs.yml
- .github/workflows/run-tests.yml
- README.md
- docs/api.md
- docs/api/gef.md
- docs/commands/gef.md
- docs/commands/pcustom.md
- docs/commands/trace-run.md
- docs/compat.md
- docs/faq.md
- docs/index.md
- docs/install.md
- gef.py
- scripts/gef.sh
- tests/api/misc.py
- tests/commands/syscall_args.py
> `master` -> `main`

- gef.py
| x86-32       | :x:                      | Replace with :white_check_mark: if tested |
| x86-64       | :x:                      |                                           |
| ARM          | :x:                      |                                           |
| AARCH64      | :x:                      |                                           |
| MIPS         | :x:                      |                                           |
| POWERPC      | :x:                      |                                           |
| SPARC        | :x:                      |                                           |
| …
> fix typo in patch byte help

- gef.py
missed return __init__ SearchPatternCommand
> missed return __init__ SearchPatternCommand

- gef.py
> Remove deprecated use of checksec()

- docs/functions/base.md
> Fix typo in docs/functions/base.md

- gef.py
> fix: make sure that heap_addr is aligned

- docs/api/gef.md
- scripts/new-release.py
> [docs] Regenerating `api/gef.md`

- docs/commands/nop.md
- gef.py
> nop: Add force req when not already --f

- docs/debugging.md
- mkdocs.yml
add debugging instructions: pycharm + pdb
> add debugging instructions

- .github/workflows/coverage.yml
curl is not installed by default on ubuntu, so just add curl to apt-get install 
https://releases.ubuntu.com/jammy/ubuntu-22.04.3-desktop-amd64.manifest
> install curl coverage.yml

- .github/workflows/coverage.yml
- .github/workflows/generate-docs.yml
- docs/testing.md
> Update rpyc example in `docs/testing.md`

- .github/workflows/validate.yml
- docs/deprecated.md
Fixed links in `docs/deprecated.md`
Also ignore search engine paths
> Fixed 404 links in `docs/deprecated.md`

- mkdocs.yml
> add skipi to docs

- .github/workflows/validate.yml
- docs/testing.md
Added documentation on how to use `pre-commit` for GEF
Fixes #1063
> [Docs] `pre-commit` setup and use

- gef.py
-  [ ] My code follows the code style of this project.
-  [ ] My change includes a change to the documentation, if required.
-  [ ] I have read and agree to the **CONTRIBUTING** document.
> Reload settings if gef-extras scripts were loaded

- docs/commands/arch.md
- mkdocs.yml
Update arch command documentation
> [cmd] Update arch command documentation

- LICENSE
- gef.py
Being in July 2024, I think it's fair to acknowledge 2024 isn't going anywhere. So let's update the license
> [License] 2023 -> 2024

- .github/workflows/coverage.yml
- LICENSE
- README.md
- gef.py
Minor fixes for the 2025.01 release
> Fixes for release 2025.01

- scripts/gef.sh
As a GDB user I need to keep my existing config when installing GEF
The `~/.gdbinit` content is currently completely removed
Still happy to keep my GDB config while it's now powered by GEF!
Replaced move with copy for the backup
[Upgrade] Check if GEF is already sourced, and replace version
[Install] Add GEF script at 1st line
> Install/update sh script: Avoid overwriting existing gdb config
